/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function CrossBeltModel(props) {
  const group = useRef();
  const { nodes, materials, animations,scene } = useGLTF("/croosbeltsort.glb");
  const { actions } = useAnimations(animations, group);


  return (
    <group ref={group} {...props} dispose={null} position={[0,0,1]} scale={[0.03,0.03,0.03]}>
      <group name="Scene">
        <group
          name="62001_(Layer_0)005"
          position={[-6.201, 7.868, -1.652]}
          rotation={[0.019, 0, 0]}
        />
        <group
          name="62001_(Layer_0)001"
          position={[-4.236, -0.01, -21.774]}
          rotation={[0, 0.791, 0]}
        />
        <group name="62001_(Layer_0)002" />
        <group name="62001_(Layer_0)003" position={[-7.75, 0, -9.769]} />
        <group name="62001_(Layer_0)004" position={[-26.676, 7.907, -10.288]} />
        <group
          name="Handle_Cube002"
          position={[5.129, 10.723, 2.031]}
          rotation={[2.854, 0, -3.127]}
        />
        <mesh
          name="Escalera_ensamblada_Escalera_1236715002"
          castShadow
          receiveShadow
          geometry={nodes.Escalera_ensamblada_Escalera_1236715002.geometry}
          material={materials["Paint Matte Grey #73"]}
          position={[0, 0, -17.639]}
        />
        <mesh
          name="ID139"
          castShadow
          receiveShadow
          geometry={nodes.ID139.geometry}
          material={materials["Paint Gloss Yellow  #70"]}
          position={[0, 0, -17.639]}
        />
        <mesh
          name="ID139001"
          castShadow
          receiveShadow
          geometry={nodes.ID139001.geometry}
          material={materials["Paint Gloss Yellow  #71"]}
          position={[0, 0, -17.639]}
        />
        <mesh
          name="Construction_Stairs-Precision_Ladders-Ships_Ladder_Cros_086001"
          castShadow
          receiveShadow
          geometry={
            nodes[
              "Construction_Stairs-Precision_Ladders-Ships_Ladder_Cros_086001"
            ].geometry
          }
          material={materials["Paint Gloss Yellow #348.144"]}
          position={[0, 0, -17.639]}
        />
        <mesh
          name="Construction_Stairs-Precision_Ladders-Ships_Ladder_Cros_8af001"
          castShadow
          receiveShadow
          geometry={
            nodes[
              "Construction_Stairs-Precision_Ladders-Ships_Ladder_Cros_8af001"
            ].geometry
          }
          material={materials["Paint Gloss Yellow #348.145"]}
          position={[0, 0, -17.639]}
        />
        <mesh
          name="Construction_Stairs-Precision_Ladders-Ships_Ladder_Cros_99f001"
          castShadow
          receiveShadow
          geometry={
            nodes[
              "Construction_Stairs-Precision_Ladders-Ships_Ladder_Cros_99f001"
            ].geometry
          }
          material={materials["Paint Gloss Yellow #348.146"]}
          position={[0, 0, -17.639]}
        />
        <mesh
          name="Construction_Stairs-Precision_Ladders-Ships_Ladder_Cros_3cd001"
          castShadow
          receiveShadow
          geometry={
            nodes[
              "Construction_Stairs-Precision_Ladders-Ships_Ladder_Cros_3cd001"
            ].geometry
          }
          material={materials["Paint Gloss Yellow #348.147"]}
          position={[0, 0, -17.639]}
        />
        <mesh
          name="Construction_Stairs-Precision_Ladders-Ships_Ladder_Cros_e01001"
          castShadow
          receiveShadow
          geometry={
            nodes[
              "Construction_Stairs-Precision_Ladders-Ships_Ladder_Cros_e01001"
            ].geometry
          }
          material={materials["Paint Gloss Yellow #348.148"]}
          position={[0, 0, -17.639]}
        />
        <mesh
          name="Construction_Stairs-Precision_Ladders-Ships_Ladder_Cros_df6001"
          castShadow
          receiveShadow
          geometry={
            nodes[
              "Construction_Stairs-Precision_Ladders-Ships_Ladder_Cros_df6001"
            ].geometry
          }
          material={materials["Paint Gloss Yellow #348.149"]}
          position={[0, 0, -17.639]}
        />
        <mesh
          name="Construction_Stairs-Precision_Ladders-Ships_Ladder_Cros_da8001"
          castShadow
          receiveShadow
          geometry={
            nodes[
              "Construction_Stairs-Precision_Ladders-Ships_Ladder_Cros_da8001"
            ].geometry
          }
          material={materials["Paint Gloss Yellow #348.150"]}
          position={[0, 0, -17.639]}
        />
        <mesh
          name="Construction_Stairs-Precision_Ladders-Ships_Ladder_Cros_cf6001"
          castShadow
          receiveShadow
          geometry={
            nodes[
              "Construction_Stairs-Precision_Ladders-Ships_Ladder_Cros_cf6001"
            ].geometry
          }
          material={materials["Paint Gloss Yellow #348.151"]}
          position={[0, 0, -17.639]}
        />
        <mesh
          name="Construction_Stairs-Precision_Ladders-Ships_Ladder_Cros_533001"
          castShadow
          receiveShadow
          geometry={
            nodes[
              "Construction_Stairs-Precision_Ladders-Ships_Ladder_Cros_533001"
            ].geometry
          }
          material={materials["Paint Gloss Yellow #348.152"]}
          position={[0, 0, -17.639]}
        />
        <mesh
          name="Construction_Stairs-Precision_Ladders-Ships_Ladder_Cros_87d001"
          castShadow
          receiveShadow
          geometry={
            nodes[
              "Construction_Stairs-Precision_Ladders-Ships_Ladder_Cros_87d001"
            ].geometry
          }
          material={materials["Paint Gloss Yellow #348.153"]}
          position={[0, 0, -17.639]}
        />
        <mesh
          name="paso_hombre_Crossover_1308350001"
          castShadow
          receiveShadow
          geometry={nodes.paso_hombre_Crossover_1308350001.geometry}
          material={materials["Paint Gloss Yellow #4"]}
          position={[0, 0, -17.639]}
        />
        <mesh
          name="paso_hombre_Crossover_1308350_1"
          castShadow
          receiveShadow
          geometry={nodes.paso_hombre_Crossover_1308350_1.geometry}
          material={materials["Paint Gloss Yellow #5"]}
          position={[0, 0, -17.639]}
        />
        <mesh
          name="paso_hombre_Crossover_1308350002"
          castShadow
          receiveShadow
          geometry={nodes.paso_hombre_Crossover_1308350002.geometry}
          material={materials["Paint Gloss Yellow #11"]}
          position={[0, 0, -17.639]}
        />
        <mesh
          name="paso_hombre_Crossover_1308350_1001"
          castShadow
          receiveShadow
          geometry={nodes.paso_hombre_Crossover_1308350_1001.geometry}
          material={materials["Paint Gloss Yellow #12"]}
          position={[0, 0, -17.639]}
        />
        <mesh
          name="paso_hombre_Crossover_1308350003"
          castShadow
          receiveShadow
          geometry={nodes.paso_hombre_Crossover_1308350003.geometry}
          material={materials["Paint Gloss Yellow #29"]}
          position={[0, 0, -17.639]}
        />
        <mesh
          name="paso_hombre_Crossover_1308350_1002"
          castShadow
          receiveShadow
          geometry={nodes.paso_hombre_Crossover_1308350_1002.geometry}
          material={materials["Paint Gloss Yellow #30"]}
          position={[0, 0, -17.639]}
        />
        <mesh
          name="paso_hombre_Crossover_1308350004"
          castShadow
          receiveShadow
          geometry={nodes.paso_hombre_Crossover_1308350004.geometry}
          material={materials["Paint Gloss Yellow #31"]}
          position={[0, 0, -17.639]}
        />
        <mesh
          name="paso_hombre_Crossover_1308350_1003"
          castShadow
          receiveShadow
          geometry={nodes.paso_hombre_Crossover_1308350_1003.geometry}
          material={materials["Paint Gloss Yellow #32"]}
          position={[0, 0, -17.639]}
        />
        <mesh
          name="Escalera_ensamblada_Escalera_1248001_1009"
          castShadow
          receiveShadow
          geometry={nodes.Escalera_ensamblada_Escalera_1248001_1009.geometry}
          material={materials["Paint Matte Grey #73.001"]}
          position={[0, 0, -17.639]}
        />
        <mesh
          name="Escalera_ensamblada_Escalera_1248001_1010"
          castShadow
          receiveShadow
          geometry={nodes.Escalera_ensamblada_Escalera_1248001_1010.geometry}
          material={materials["Paint Matte Grey #73.002"]}
          position={[0, 0, -17.639]}
        />
        <mesh
          name="Escalera_ensamblada_Escalera_1257247002"
          castShadow
          receiveShadow
          geometry={nodes.Escalera_ensamblada_Escalera_1257247002.geometry}
          material={materials["Paint Matte Grey #73.003"]}
          position={[0, 0, -17.639]}
        />
        <mesh
          name="Suelo_Generic_Floor_-_100mm_2_1217029_1"
          castShadow
          receiveShadow
          geometry={nodes["Suelo_Generic_Floor_-_100mm_2_1217029_1"].geometry}
          material={materials["Paint Matte Grey #73.004"]}
          position={[0, 0, -17.639]}
        />
        <mesh
          name="Suelo_Generic_Floor_-_100mm_2_1217029_2"
          castShadow
          receiveShadow
          geometry={nodes["Suelo_Generic_Floor_-_100mm_2_1217029_2"].geometry}
          material={materials["Paint Matte Grey #73.005"]}
          position={[0, 0, -17.639]}
        />
        <mesh
          name="Suelo_Generic_Floor_-_100mm_2_1217029002"
          castShadow
          receiveShadow
          geometry={nodes["Suelo_Generic_Floor_-_100mm_2_1217029002"].geometry}
          material={materials["Paint Matte Grey #73.006"]}
          position={[0, 0, -17.639]}
        />
        <mesh
          name="Suelo_Generic_Floor_-_100mm_2_1217029_1001"
          castShadow
          receiveShadow
          geometry={
            nodes["Suelo_Generic_Floor_-_100mm_2_1217029_1001"].geometry
          }
          material={materials["Paint Matte Grey #73.007"]}
          position={[0, 0, -17.639]}
        />
        <group name="Suelo_Generic_Floor_-_100mm_2_1217029_1010" />
        <mesh
          name="Suelo_Generic_Floor_-_100mm_2_1217029_1011"
          castShadow
          receiveShadow
          geometry={
            nodes["Suelo_Generic_Floor_-_100mm_2_1217029_1011"].geometry
          }
          material={materials["Paint Matte Grey #73.017"]}
          position={[0, 0, -17.639]}
        />
        <mesh
          name="Suelo_Generic_Floor_-_100mm_2_1252737001"
          castShadow
          receiveShadow
          geometry={nodes["Suelo_Generic_Floor_-_100mm_2_1252737001"].geometry}
          material={materials["Paint Matte Grey #73.018"]}
          position={[0, 0, -17.639]}
        />
        <mesh
          name="Suelo_Generic_Floor_-_100mm_2_1252737_1001"
          castShadow
          receiveShadow
          geometry={
            nodes["Suelo_Generic_Floor_-_100mm_2_1252737_1001"].geometry
          }
          material={materials["Paint Matte Grey #73.020"]}
          position={[0, 0, -17.639]}
        />
        <mesh
          name="Suelo_Generic_Floor_-_100mm_2_1217029_1012"
          castShadow
          receiveShadow
          geometry={
            nodes["Suelo_Generic_Floor_-_100mm_2_1217029_1012"].geometry
          }
          material={materials["METAL AMARILLO"]}
          position={[0, 0, -17.639]}
        />
        <mesh
          name="Suelo_Generic_Floor_-_100mm_2_1217029_1013"
          castShadow
          receiveShadow
          geometry={
            nodes["Suelo_Generic_Floor_-_100mm_2_1217029_1013"].geometry
          }
          material={materials["METAL AMARILLO"]}
          position={[0, 0, -17.639]}
        />
        <mesh
          name="Suelo_Generic_Floor_-_100mm_2_1217029003"
          castShadow
          receiveShadow
          geometry={nodes["Suelo_Generic_Floor_-_100mm_2_1217029003"].geometry}
          material={materials["METAL AMARILLO"]}
          position={[0, 0.012, -17.639]}
        />
        <mesh
          name="Suelo_Generic_Floor_-_100mm_2_1217029004"
          castShadow
          receiveShadow
          geometry={nodes["Suelo_Generic_Floor_-_100mm_2_1217029004"].geometry}
          material={materials["METAL AMARILLO"]}
          position={[0, 0, -17.639]}
        />
        <mesh
          name="Suelo_Generic_Floor_-_100mm_2_1217029005"
          castShadow
          receiveShadow
          geometry={nodes["Suelo_Generic_Floor_-_100mm_2_1217029005"].geometry}
          material={materials["METAL AMARILLO"]}
          position={[0, 0, -17.639]}
        />
        <mesh
          name="Suelo_Generic_Floor_-_100mm_2_1217029006"
          castShadow
          receiveShadow
          geometry={nodes["Suelo_Generic_Floor_-_100mm_2_1217029006"].geometry}
          material={materials["Material.002"]}
          position={[0, 0, -17.639]}
        />
        <mesh
          name="Suelo_Generic_Floor_-_100mm_2_1217029_2001"
          castShadow
          receiveShadow
          geometry={
            nodes["Suelo_Generic_Floor_-_100mm_2_1217029_2001"].geometry
          }
          material={materials["METAL AMARILLO"]}
          position={[0, 0, -17.639]}
        />
        <mesh
          name="Suelo_Generic_Floor_-_100mm_2_1217029_1014"
          castShadow
          receiveShadow
          geometry={
            nodes["Suelo_Generic_Floor_-_100mm_2_1217029_1014"].geometry
          }
          material={materials["METAL AMARILLO"]}
          position={[0, 0, -17.639]}
        />
        <mesh
          name="Suelo_Generic_Floor_-_100mm_2_1217029008"
          castShadow
          receiveShadow
          geometry={nodes["Suelo_Generic_Floor_-_100mm_2_1217029008"].geometry}
          material={materials["METAL AMARILLO"]}
          position={[0, 0, -17.639]}
        />
        <mesh
          name="Suelo_Generic_Floor_-_100mm_2_1217029_1015"
          castShadow
          receiveShadow
          geometry={
            nodes["Suelo_Generic_Floor_-_100mm_2_1217029_1015"].geometry
          }
          material={materials["METAL AMARILLO"]}
          position={[0, 0, -17.639]}
        />
        <mesh
          name="Suelo_Generic_Floor_-_100mm_2_1217029_1016"
          castShadow
          receiveShadow
          geometry={
            nodes["Suelo_Generic_Floor_-_100mm_2_1217029_1016"].geometry
          }
          material={materials["METAL AMARILLO"]}
          position={[0, 0, -17.639]}
        />
        <mesh
          name="Suelo_Generic_Floor_-_100mm_2_1217029_1017"
          castShadow
          receiveShadow
          geometry={
            nodes["Suelo_Generic_Floor_-_100mm_2_1217029_1017"].geometry
          }
          material={materials["METAL AMARILLO"]}
          position={[0, 0, -17.639]}
        />
        <mesh
          name="Suelo_Generic_Floor_-_100mm_2_1252737002"
          castShadow
          receiveShadow
          geometry={nodes["Suelo_Generic_Floor_-_100mm_2_1252737002"].geometry}
          material={materials["METAL AMARILLO"]}
          position={[0, 0, -17.639]}
        />
        <mesh
          name="Suelo_Generic_Floor_-_100mm_2_1252737_1002"
          castShadow
          receiveShadow
          geometry={
            nodes["Suelo_Generic_Floor_-_100mm_2_1252737_1002"].geometry
          }
          material={materials["METAL AMARILLO"]}
          position={[0, 0, -17.639]}
        />
        <mesh
          name="Suelo_Generic_Floor_-_100mm_2_1217029_1018"
          castShadow
          receiveShadow
          geometry={
            nodes["Suelo_Generic_Floor_-_100mm_2_1217029_1018"].geometry
          }
          material={materials["METAL AMARILLO"]}
          position={[0, 0, -17.639]}
        />
        <mesh
          name="Suelo_Generic_Floor_-_100mm_2_1217029_1019"
          castShadow
          receiveShadow
          geometry={
            nodes["Suelo_Generic_Floor_-_100mm_2_1217029_1019"].geometry
          }
          material={materials["METAL AMARILLO"]}
          position={[0, 0, -17.639]}
        />
        <mesh
          name="Suelo_Generic_Floor_-_100mm_2_1217029_1020"
          castShadow
          receiveShadow
          geometry={
            nodes["Suelo_Generic_Floor_-_100mm_2_1217029_1020"].geometry
          }
          material={materials["METAL AMARILLO"]}
          position={[0, 0, -17.639]}
        />
        <mesh
          name="Suelo_Generic_Floor_-_100mm_2_1217029009"
          castShadow
          receiveShadow
          geometry={nodes["Suelo_Generic_Floor_-_100mm_2_1217029009"].geometry}
          material={materials["METAL AMARILLO"]}
          position={[0, 0, -17.639]}
        />
        <mesh
          name="Suelo_Generic_Floor_-_100mm_2_1217029_1021"
          castShadow
          receiveShadow
          geometry={
            nodes["Suelo_Generic_Floor_-_100mm_2_1217029_1021"].geometry
          }
          material={materials["METAL AMARILLO"]}
          position={[0, 0, -17.639]}
        />
        <mesh
          name="Suelo_Generic_Floor_-_100mm_2_1217029010"
          castShadow
          receiveShadow
          geometry={nodes["Suelo_Generic_Floor_-_100mm_2_1217029010"].geometry}
          material={materials["METAL AMARILLO"]}
          position={[0, 0, -17.639]}
        />
        <mesh
          name="Suelo_Generic_Floor_-_100mm_2_1217029011"
          castShadow
          receiveShadow
          geometry={nodes["Suelo_Generic_Floor_-_100mm_2_1217029011"].geometry}
          material={materials["METAL AMARILLO"]}
          position={[0, 0, -17.639]}
        />
        <mesh
          name="Suelo_Generic_Floor_-_100mm_2_1217029012"
          castShadow
          receiveShadow
          geometry={nodes["Suelo_Generic_Floor_-_100mm_2_1217029012"].geometry}
          material={materials["METAL AMARILLO"]}
          position={[0, 0, -17.639]}
        />
        <mesh
          name="Suelo_Generic_Floor_-_100mm_2_1217029013"
          castShadow
          receiveShadow
          geometry={nodes["Suelo_Generic_Floor_-_100mm_2_1217029013"].geometry}
          material={materials["METAL AMARILLO"]}
          position={[0, 0, -17.639]}
        />
        <mesh
          name="Suelo_Generic_Floor_-_100mm_2_1217029014"
          castShadow
          receiveShadow
          geometry={nodes["Suelo_Generic_Floor_-_100mm_2_1217029014"].geometry}
          material={materials["METAL AMARILLO"]}
          position={[0, 0, -17.639]}
        />
        <mesh
          name="Suelo_Generic_Floor_-_100mm_2_1217029015"
          castShadow
          receiveShadow
          geometry={nodes["Suelo_Generic_Floor_-_100mm_2_1217029015"].geometry}
          material={materials["METAL AMARILLO"]}
          position={[0, 0, -17.639]}
        />
        <mesh
          name="Suelo_Generic_Floor_-_100mm_2_1217029_1022"
          castShadow
          receiveShadow
          geometry={
            nodes["Suelo_Generic_Floor_-_100mm_2_1217029_1022"].geometry
          }
          material={materials["METAL AMARILLO"]}
          position={[0, 0, -17.639]}
        />
        <mesh
          name="Suelo_Generic_Floor_-_100mm_2_1217029007"
          castShadow
          receiveShadow
          geometry={nodes["Suelo_Generic_Floor_-_100mm_2_1217029007"].geometry}
          material={materials["METAL AMARILLO"]}
          position={[0, 0, -17.639]}
        />
        <mesh
          name="Cylinder430"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder430.geometry}
          material={nodes.Cylinder430.material}
          position={[-48.316, 8.283, -63.294]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={[0.574, 0.574, 2.543]}
        />
        <mesh
          name="Cylinder431"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder431.geometry}
          material={nodes.Cylinder431.material}
          position={[-49.305, 8.283, -63.294]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={[0.574, 0.574, 2.543]}
        />
        <mesh
          name="Cylinder432"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder432.geometry}
          material={nodes.Cylinder432.material}
          position={[-49.305, 8.283, -64.421]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={[0.574, 0.574, 2.543]}
        />
        <mesh
          name="Cylinder433"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder433.geometry}
          material={nodes.Cylinder433.material}
          position={[-47.198, 8.244, -63.285]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={[0.568, 0.568, 2.516]}
        />
        <mesh
          name="Cylinder434"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder434.geometry}
          material={nodes.Cylinder434.material}
          position={[-46.432, 8.244, -63.285]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={[0.568, 0.568, 2.516]}
        />
        <mesh
          name="Cylinder435"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder435.geometry}
          material={nodes.Cylinder435.material}
          position={[-66.083, 7.86, -64.431]}
          rotation={[0, 0, Math.PI]}
          scale={[0.724, 0.724, 3.206]}
        />
        <mesh
          name="Cylinder436"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder436.geometry}
          material={nodes.Cylinder436.material}
          position={[-66.436, 8.283, -64.442]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={[0.574, 0.574, 2.543]}
        />
        <mesh
          name="Cylinder437"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder437.geometry}
          material={nodes.Cylinder437.material}
          position={[-67.201, 8.283, -64.442]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={[0.574, 0.574, 2.543]}
        />
        <mesh
          name="Cylinder488"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder488.geometry}
          material={nodes.Cylinder488.material}
          position={[-39.089, 8.363, -65.822]}
          rotation={[-1.571, 0.012, Math.PI / 2]}
          scale={[0.724, 0.723, 0.197]}
        />
        <mesh
          name="Cylinder498"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder498.geometry}
          material={nodes.Cylinder498.material}
          position={[-39.089, 8.363, -65.792]}
          rotation={[-1.571, 0.012, Math.PI / 2]}
          scale={[0.724, 0.723, 0.197]}
        />
        <mesh
          name="Cylinder499"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder499.geometry}
          material={materials["Material.002"]}
          position={[-39.089, 8.363, -66.881]}
          rotation={[-1.571, 0.012, Math.PI / 2]}
          scale={[0.724, 0.723, 0.197]}
        />
        <mesh
          name="Cylinder508"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder508.geometry}
          material={nodes.Cylinder508.material}
          position={[-86.223, 8.363, -68.012]}
          rotation={[-1.571, 0.012, Math.PI / 2]}
          scale={[0.724, 0.723, 0.197]}
        />
        <mesh
          name="Cylinder518"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder518.geometry}
          material={materials["Material.002"]}
          position={[-94.943, 8.363, -66.675]}
          rotation={[-1.571, 0.012, Math.PI / 2]}
          scale={[0.724, 0.723, 0.197]}
        />
        <mesh
          name="Cylinder556"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder556.geometry}
          material={nodes.Cylinder556.material}
          position={[-46.13, 8.302, -59.298]}
          rotation={[-1.571, 0.012, Math.PI / 2]}
          scale={[0.724, 0.769, 0.197]}
        />
        <mesh
          name="Cylinder557"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder557.geometry}
          material={nodes.Cylinder557.material}
          position={[-46.859, 8.302, -59.298]}
          rotation={[-1.571, 0.012, Math.PI / 2]}
          scale={[0.724, 0.769, 0.197]}
        />
        <mesh
          name="Cylinder558"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder558.geometry}
          material={nodes.Cylinder558.material}
          position={[-48.001, 8.363, -59.31]}
          rotation={[-1.571, 0.012, Math.PI / 2]}
          scale={[0.724, 0.723, 0.197]}
        />
        <mesh
          name="Cylinder559"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder559.geometry}
          material={nodes.Cylinder559.material}
          position={[-49.835, 8.363, -59.31]}
          rotation={[-1.571, 0.012, Math.PI / 2]}
          scale={[0.724, 0.723, 0.197]}
        />
        <mesh
          name="Cylinder560"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder560.geometry}
          material={nodes.Cylinder560.material}
          position={[-62.275, 8.363, -58.255]}
          rotation={[-1.571, 0.012, Math.PI / 2]}
          scale={[0.724, 0.723, 0.197]}
        />
        <mesh
          name="Cylinder561"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder561.geometry}
          material={nodes.Cylinder561.material}
          position={[-61.291, 8.363, -58.255]}
          rotation={[-1.571, 0.012, Math.PI / 2]}
          scale={[0.724, 0.723, 0.197]}
        />
        <mesh
          name="Cylinder562"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder562.geometry}
          material={nodes.Cylinder562.material}
          position={[-60.268, 8.363, -58.255]}
          rotation={[-1.571, 0.012, Math.PI / 2]}
          scale={[0.724, 0.723, 0.197]}
        />
        <mesh
          name="Cylinder563"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder563.geometry}
          material={nodes.Cylinder563.material}
          position={[-59.261, 8.363, -58.255]}
          rotation={[-1.571, 0.012, Math.PI / 2]}
          scale={[0.724, 0.723, 0.197]}
        />
        <mesh
          name="Cylinder564"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder564.geometry}
          material={nodes.Cylinder564.material}
          position={[-58.27, 8.363, -58.255]}
          rotation={[-1.571, 0.012, Math.PI / 2]}
          scale={[0.724, 0.723, 0.197]}
        />
        <mesh
          name="Cylinder565"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder565.geometry}
          material={nodes.Cylinder565.material}
          position={[-57.275, 8.363, -58.255]}
          rotation={[-1.571, 0.012, Math.PI / 2]}
          scale={[0.724, 0.723, 0.197]}
        />
        <mesh
          name="Cylinder566"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder566.geometry}
          material={nodes.Cylinder566.material}
          position={[-56.262, 8.363, -58.255]}
          rotation={[-1.571, 0.012, Math.PI / 2]}
          scale={[0.724, 0.723, 0.197]}
        />
        <mesh
          name="Cylinder567"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder567.geometry}
          material={nodes.Cylinder567.material}
          position={[-55.29, 8.363, -58.255]}
          rotation={[-1.571, 0.012, Math.PI / 2]}
          scale={[0.724, 0.723, 0.197]}
        />
        <mesh
          name="Cylinder568"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder568.geometry}
          material={nodes.Cylinder568.material}
          position={[-54.271, 8.363, -58.255]}
          rotation={[-1.571, 0.012, Math.PI / 2]}
          scale={[0.724, 0.723, 0.197]}
        />
        <mesh
          name="Cylinder569"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder569.geometry}
          material={nodes.Cylinder569.material}
          position={[-53.269, 8.363, -58.255]}
          rotation={[-1.571, 0.012, Math.PI / 2]}
          scale={[0.724, 0.723, 0.197]}
        />
        <mesh
          name="Cylinder570"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder570.geometry}
          material={nodes.Cylinder570.material}
          position={[-52.02, 8.363, -58.255]}
          rotation={[-1.571, 0.012, Math.PI / 2]}
          scale={[0.724, 0.723, 0.197]}
        />
        <mesh
          name="Cylinder571"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder571.geometry}
          material={nodes.Cylinder571.material}
          position={[-50.883, 8.363, -58.255]}
          rotation={[-1.571, 0.012, Math.PI / 2]}
          scale={[0.724, 0.723, 0.197]}
        />
        <mesh
          name="Cylinder572"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder572.geometry}
          material={nodes.Cylinder572.material}
          position={[-63.412, 8.363, -58.255]}
          rotation={[-1.571, 0.012, Math.PI / 2]}
          scale={[0.724, 0.723, 0.197]}
        />
        <mesh
          name="Cylinder573"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder573.geometry}
          material={nodes.Cylinder573.material}
          position={[-82.484, 8.363, -58.255]}
          rotation={[-1.571, 0.012, Math.PI / 2]}
          scale={[0.724, 0.723, 0.197]}
        />
        <mesh
          name="Cylinder574"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder574.geometry}
          material={nodes.Cylinder574.material}
          position={[-81.499, 8.363, -58.255]}
          rotation={[-1.571, 0.012, Math.PI / 2]}
          scale={[0.724, 0.723, 0.197]}
        />
        <mesh
          name="Cylinder575"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder575.geometry}
          material={nodes.Cylinder575.material}
          position={[-80.477, 8.363, -58.255]}
          rotation={[-1.571, 0.012, Math.PI / 2]}
          scale={[0.724, 0.723, 0.197]}
        />
        <mesh
          name="Cylinder576"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder576.geometry}
          material={nodes.Cylinder576.material}
          position={[-79.47, 8.363, -58.255]}
          rotation={[-1.571, 0.012, Math.PI / 2]}
          scale={[0.724, 0.723, 0.197]}
        />
        <mesh
          name="Cylinder577"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder577.geometry}
          material={nodes.Cylinder577.material}
          position={[-78.479, 8.363, -58.255]}
          rotation={[-1.571, 0.012, Math.PI / 2]}
          scale={[0.724, 0.723, 0.197]}
        />
        <mesh
          name="Cylinder578"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder578.geometry}
          material={nodes.Cylinder578.material}
          position={[-77.483, 8.363, -58.255]}
          rotation={[-1.571, 0.012, Math.PI / 2]}
          scale={[0.724, 0.723, 0.197]}
        />
        <mesh
          name="Cylinder579"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder579.geometry}
          material={nodes.Cylinder579.material}
          position={[-76.471, 8.363, -58.255]}
          rotation={[-1.571, 0.012, Math.PI / 2]}
          scale={[0.724, 0.723, 0.197]}
        />
        <mesh
          name="Cylinder580"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder580.geometry}
          material={nodes.Cylinder580.material}
          position={[-75.498, 8.363, -58.255]}
          rotation={[-1.571, 0.012, Math.PI / 2]}
          scale={[0.724, 0.723, 0.197]}
        />
        <mesh
          name="Cylinder581"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder581.geometry}
          material={nodes.Cylinder581.material}
          position={[-74.479, 8.363, -58.255]}
          rotation={[-1.571, 0.012, Math.PI / 2]}
          scale={[0.724, 0.723, 0.197]}
        />
        <mesh
          name="Cylinder582"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder582.geometry}
          material={nodes.Cylinder582.material}
          position={[-73.477, 8.363, -58.255]}
          rotation={[-1.571, 0.012, Math.PI / 2]}
          scale={[0.724, 0.723, 0.197]}
        />
        <mesh
          name="Cylinder583"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder583.geometry}
          material={nodes.Cylinder583.material}
          position={[-72.228, 8.363, -58.255]}
          rotation={[-1.571, 0.012, Math.PI / 2]}
          scale={[0.724, 0.723, 0.197]}
        />
        <mesh
          name="Cylinder584"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder584.geometry}
          material={nodes.Cylinder584.material}
          position={[-71.092, 8.363, -58.255]}
          rotation={[-1.571, 0.012, Math.PI / 2]}
          scale={[0.724, 0.723, 0.197]}
        />
        <mesh
          name="Cylinder585"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder585.geometry}
          material={nodes.Cylinder585.material}
          position={[-83.62, 8.363, -58.255]}
          rotation={[-1.571, 0.012, Math.PI / 2]}
          scale={[0.724, 0.723, 0.197]}
        />
        <mesh
          name="Cylinder586"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder586.geometry}
          material={nodes.Cylinder586.material}
          position={[-69.874, 8.363, -58.255]}
          rotation={[-1.571, 0.012, Math.PI / 2]}
          scale={[0.724, 0.723, 0.197]}
        />
        <mesh
          name="Cylinder587"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder587.geometry}
          material={nodes.Cylinder587.material}
          position={[-84.953, 8.363, -58.255]}
          rotation={[-1.571, 0.012, Math.PI / 2]}
          scale={[0.724, 0.723, 0.197]}
        />
        <mesh
          name="Cube103"
          castShadow
          receiveShadow
          geometry={nodes.Cube103.geometry}
          material={materials["Material.002"]}
          position={[-80.138, 7.19, -67.747]}
          rotation={[0, 1.571, 0]}
          scale={[0.004, 0.205, 0.045]}
        />
        <mesh
          name="Cube104"
          castShadow
          receiveShadow
          geometry={nodes.Cube104.geometry}
          material={materials["Material.002"]}
          position={[-74.226, 7.19, -67.747]}
          rotation={[0, 1.571, 0]}
          scale={[0.004, 0.205, 0.045]}
        />
        <mesh
          name="Cube107"
          castShadow
          receiveShadow
          geometry={nodes.Cube107.geometry}
          material={materials["Material.002"]}
          position={[-59.609, 7.19, -67.747]}
          rotation={[0, 1.571, 0]}
          scale={[0.004, 0.205, 0.045]}
        />
        <mesh
          name="Cube108"
          castShadow
          receiveShadow
          geometry={nodes.Cube108.geometry}
          material={materials["Material.002"]}
          position={[-53.623, 7.19, -67.747]}
          rotation={[0, 1.571, 0]}
          scale={[0.004, 0.205, 0.045]}
        />
        <mesh
          name="Cube109"
          castShadow
          receiveShadow
          geometry={nodes.Cube109.geometry}
          material={materials["Material.002"]}
          position={[-59.609, 7.19, -64.438]}
          rotation={[0, 1.571, 0]}
          scale={[0.004, 0.205, 0.045]}
        />
        <mesh
          name="Cube292"
          castShadow
          receiveShadow
          geometry={nodes.Cube292.geometry}
          material={materials["Material.002"]}
          position={[-53.623, 7.19, -64.438]}
          rotation={[0, 1.571, 0]}
          scale={[0.004, 0.205, 0.045]}
        />
        <mesh
          name="Cube295"
          castShadow
          receiveShadow
          geometry={nodes.Cube295.geometry}
          material={materials["Material.002"]}
          position={[-53.497, 7.19, -54.645]}
          rotation={[0, 1.571, 0]}
          scale={[0.004, 0.205, 0.045]}
        />
        <mesh
          name="Cube305"
          castShadow
          receiveShadow
          geometry={nodes.Cube305.geometry}
          material={materials["Material.002"]}
          position={[-80.158, 7.133, -58.119]}
          rotation={[0, 1.571, 0]}
          scale={[0.004, 0.205, 0.045]}
        />
        <mesh
          name="Cube306"
          castShadow
          receiveShadow
          geometry={nodes.Cube306.geometry}
          material={materials["Material.002"]}
          position={[-74.209, 7.133, -58.119]}
          rotation={[0, 1.571, 0]}
          scale={[0.004, 0.205, 0.045]}
        />
        <group
          name="Símbolo_de_importación_ubicación_<No_compartido>_12_1e4005"
          position={[0, 0, -17.639]}
        >
          <mesh
            name="mesh396"
            castShadow
            receiveShadow
            geometry={nodes.mesh396.geometry}
            material={materials.METAL}
          />
          <mesh
            name="mesh396_1"
            castShadow
            receiveShadow
            geometry={nodes.mesh396_1.geometry}
            material={materials["Negro.001"]}
          />
        </group>
        <group
          name="Símbolo_de_importación_ubicación_<No_compartido>_12_1e4004"
          position={[0, 0, -17.639]}
        >
          <mesh
            name="mesh397"
            castShadow
            receiveShadow
            geometry={nodes.mesh397.geometry}
            material={materials.METAL}
          />
          <mesh
            name="mesh397_1"
            castShadow
            receiveShadow
            geometry={nodes.mesh397_1.geometry}
            material={materials["Negro.001"]}
          />
        </group>
        <group name="Suelo_ANDENES_656127004" position={[0, 0, -64.191]} />
        <group name="g31006" position={[0, 0, -17.639]}>
          <mesh
            name="mesh4129"
            castShadow
            receiveShadow
            geometry={nodes.mesh4129.geometry}
            material={materials.METAL}
          />
          <mesh
            name="mesh4129_1"
            castShadow
            receiveShadow
            geometry={nodes.mesh4129_1.geometry}
            material={materials["Negro.001"]}
          />
        </group>
        <group name="g31007" position={[0, 0, -17.639]}>
          <mesh
            name="mesh4953"
            castShadow
            receiveShadow
            geometry={nodes.mesh4953.geometry}
            material={materials.METAL}
          />
          <mesh
            name="mesh4953_1"
            castShadow
            receiveShadow
            geometry={nodes.mesh4953_1.geometry}
            material={materials["Negro.001"]}
          />
        </group>
        <group name="g31008" position={[0, 0, -17.639]}>
          <mesh
            name="mesh4954"
            castShadow
            receiveShadow
            geometry={nodes.mesh4954.geometry}
            material={materials.METAL}
          />
          <mesh
            name="mesh4954_1"
            castShadow
            receiveShadow
            geometry={nodes.mesh4954_1.geometry}
            material={materials["Negro.001"]}
          />
        </group>
        <mesh
          name="Curva"
          castShadow
          receiveShadow
          geometry={nodes.Curva.geometry}
          material={materials["Negro.001"]}
          position={[0, 0, -17.639]}
        />
        <mesh
          name="10202_(Layer_0)011"
          castShadow
          receiveShadow
          geometry={nodes["10202_(Layer_0)011"].geometry}
          material={materials.METAL}
          position={[0, 0, -17.639]}
        />
        <mesh
          name="Plane075"
          castShadow
          receiveShadow
          geometry={nodes.Plane075.geometry}
          material={materials.METAL}
          position={[0, 0, -17.639]}
        />
        <group
          name="Símbolo_de_importación_ubicación_<No_compartido>_12_d6c004"
          position={[0, 0, -17.639]}
        >
          <mesh
            name="mesh382"
            castShadow
            receiveShadow
            geometry={nodes.mesh382.geometry}
            material={materials.METAL}
          />
          <mesh
            name="mesh382_1"
            castShadow
            receiveShadow
            geometry={nodes.mesh382_1.geometry}
            material={materials["Negro.001"]}
          />
        </group>
        <group
          name="Símbolo_de_importación_ubicación_<No_compartido>_12_d6c008"
          position={[0, 0, -17.639]}
        >
          <mesh
            name="mesh383"
            castShadow
            receiveShadow
            geometry={nodes.mesh383.geometry}
            material={materials.METAL}
          />
          <mesh
            name="mesh383_1"
            castShadow
            receiveShadow
            geometry={nodes.mesh383_1.geometry}
            material={materials["Negro.001"]}
          />
        </group>
        <group
          name="Símbolo_de_importación_ubicación_<No_compartido>_12_d6c009"
          position={[0, 0, -17.639]}
        >
          <mesh
            name="mesh389"
            castShadow
            receiveShadow
            geometry={nodes.mesh389.geometry}
            material={materials.METAL}
          />
          <mesh
            name="mesh389_1"
            castShadow
            receiveShadow
            geometry={nodes.mesh389_1.geometry}
            material={materials["Negro.001"]}
          />
        </group>
        <mesh
          name="Cylinder018"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder018.geometry}
          material={materials.METAL}
          position={[0, 0, -17.639]}
        />
        <mesh
          name="Cylinder038"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder038.geometry}
          material={materials.METAL}
          position={[0, 0, -17.639]}
        />
        <mesh
          name="Cylinder042"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder042.geometry}
          material={materials.METAL}
          position={[0, 0, -17.639]}
        />
        <group
          name="Símbolo_de_importación_ubicación_<No_compartido>_12_a7a004"
          position={[0, 0, -17.639]}
        >
          <mesh
            name="mesh390"
            castShadow
            receiveShadow
            geometry={nodes.mesh390.geometry}
            material={materials.METAL}
          />
          <mesh
            name="mesh390_1"
            castShadow
            receiveShadow
            geometry={nodes.mesh390_1.geometry}
            material={materials["Negro.001"]}
          />
        </group>
        <group
          name="Símbolo_de_importación_ubicación_<No_compartido>_12_a7a006"
          position={[0, 0, -17.639]}
        >
          <mesh
            name="mesh392"
            castShadow
            receiveShadow
            geometry={nodes.mesh392.geometry}
            material={materials.METAL}
          />
          <mesh
            name="mesh392_1"
            castShadow
            receiveShadow
            geometry={nodes.mesh392_1.geometry}
            material={materials["Negro.001"]}
          />
        </group>
        <mesh
          name="10202_(Layer_0)019"
          castShadow
          receiveShadow
          geometry={nodes["10202_(Layer_0)019"].geometry}
          material={materials.METAL}
          position={[0, 0, -17.639]}
        />
        <mesh
          name="10202_(Layer_0)024"
          castShadow
          receiveShadow
          geometry={nodes["10202_(Layer_0)024"].geometry}
          material={materials.METAL}
          position={[0, 0, -17.639]}
        />
        <group name="10202_(Layer_0)026" position={[0, 0, -17.639]}>
          <mesh
            name="mesh398"
            castShadow
            receiveShadow
            geometry={nodes.mesh398.geometry}
            material={materials.METAL}
          />
          <mesh
            name="mesh398_1"
            castShadow
            receiveShadow
            geometry={nodes.mesh398_1.geometry}
            material={materials["Negro.001"]}
          />
        </group>
        <group name="10202_(Layer_0)029" position={[0, 0, -17.639]}>
          <mesh
            name="mesh401"
            castShadow
            receiveShadow
            geometry={nodes.mesh401.geometry}
            material={materials.METAL}
          />
          <mesh
            name="mesh401_1"
            castShadow
            receiveShadow
            geometry={nodes.mesh401_1.geometry}
            material={materials["Negro.001"]}
          />
        </group>
        <group name="10202_(Layer_0)031" position={[0, 0, -17.639]}>
          <mesh
            name="mesh404"
            castShadow
            receiveShadow
            geometry={nodes.mesh404.geometry}
            material={materials.METAL}
          />
          <mesh
            name="mesh404_1"
            castShadow
            receiveShadow
            geometry={nodes.mesh404_1.geometry}
            material={materials["Negro.001"]}
          />
        </group>
        <group name="Cylinder043" position={[0, 0, -17.639]}>
          <mesh
            name="Cylinder616"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder616.geometry}
            material={materials.METAL}
          />
          <mesh
            name="Cylinder616_1"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder616_1.geometry}
            material={materials["Negro.001"]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/croosbeltsort.glb");
