/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function CVRAModel(props) {
  const { nodes, materials } = useGLTF("/cvracentrado.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["10202_(Layer_0)035"].geometry}
        material={materials["Low.002"]}
        position={[-60.717, 5.198, 7.759]}
        scale={[1, 1.409, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["10202_(Layer_0)065"].geometry}
        material={materials["Low.002"]}
        position={[-73.664, 4.771, 18.847]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["10202_(Layer_0)066"].geometry}
        material={materials["Low.002"]}
        position={[-71.537, 4.771, 18.815]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["10202_(Layer_0)067"].geometry}
        material={materials["Low.002"]}
        position={[-66.972, 4.811, 18.815]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["10202_(Layer_0)068"].geometry}
        material={materials["Low.002"]}
        position={[-66.441, 4.827, 18.871]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["10202_(Layer_0)069"].geometry}
        material={materials["Low.002"]}
        position={[-62.139, 4.84, 14.715]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["10202_(Layer_0)070"].geometry}
        material={materials["Low.002"]}
        position={[-62.139, 4.84, 11.316]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["10202_(Layer_0)071"].geometry}
        material={materials["Low.002"]}
        position={[-62.139, 4.84, 7.742]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["10202_(Layer_0)072"].geometry}
        material={materials["Low.002"]}
        position={[-61.151, 4.84, 14.715]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["10202_(Layer_0)073"].geometry}
        material={materials["Low.002"]}
        position={[-61.151, 4.84, 11.316]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["10202_(Layer_0)074"].geometry}
        material={materials["Low.002"]}
        position={[-61.151, 4.84, 7.742]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["10202_(Layer_0)105"].geometry}
        material={materials["Low.002"]}
        position={[-74.987, 4.771, 17.475]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["10202_(Layer_0)106"].geometry}
        material={materials["Low.002"]}
        position={[-75.001, 4.771, 17.173]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["10202_(Layer_0)107"].geometry}
        material={materials["Low.002"]}
        position={[-75.005, 4.771, 15.139]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["10202_(Layer_0)108"].geometry}
        material={materials["Low.002"]}
        position={[-75.006, 4.771, 15.365]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["10202_(Layer_0)109"].geometry}
        material={materials["Low.002"]}
        position={[-75.005, 4.771, 14.185]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["10202_(Layer_0)110"].geometry}
        material={materials["Low.002"]}
        position={[-75.006, 4.771, 13.933]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["10202_(Layer_0)111"].geometry}
        material={materials["Low.002"]}
        position={[-75.007, 4.771, 11.703]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["10202_(Layer_0)112"].geometry}
        material={materials["Low.002"]}
        position={[-75.005, 4.771, 11.487]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["10202_(Layer_0)113"].geometry}
        material={materials["Low.002"]}
        position={[-75.007, 4.771, 10.531]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["10202_(Layer_0)114"].geometry}
        material={materials["Low.002"]}
        position={[-75.006, 4.771, 10.268]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["10202_(Layer_0)115"].geometry}
        material={materials["Low.002"]}
        position={[-75.003, 4.771, 8.476]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["10202_(Layer_0)116"].geometry}
        material={materials["Low.002"]}
        position={[-71.213, 5.116, 0.715]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["10202_(Layer_0)117"].geometry}
        material={materials["Low.002"]}
        position={[-71.213, 4.903, 4.567]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["10202_(Layer_0)118"].geometry}
        material={materials["Low.002"]}
        position={[-71.213, 4.759, 7.411]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["10202_(Layer_0)119"].geometry}
        material={materials["Low.002"]}
        position={[-71.213, 4.759, 11.892]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["10202_(Layer_0)120"].geometry}
        material={materials["Low.002"]}
        position={[-71.213, 4.76, 16.772]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["10202_(Layer_0)121"].geometry}
        material={materials["Low.002"]}
        position={[-65.066, 4.828, 17.542]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["10202_(Layer_0)122"].geometry}
        material={materials["Low.002"]}
        position={[-65.056, 4.831, 17.014]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["10202_(Layer_0)123"].geometry}
        material={materials["Low.002"]}
        position={[-65.054, 4.851, 12.303]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["10202_(Layer_0)124"].geometry}
        material={materials["Low.002"]}
        position={[-65.054, 4.828, 8.055]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["10202_(Layer_0)125"].geometry}
        material={materials["Low.002"]}
        position={[-63.581, 4.817, 8.387]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["10202_(Layer_0)126"].geometry}
        material={materials["Low.002"]}
        position={[-63.581, 4.817, 12.019]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["10202_(Layer_0)127"].geometry}
        material={materials["Low.002"]}
        position={[-63.581, 4.817, 15.413]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["10202_(Layer_0)128"].geometry}
        material={materials["Low.002"]}
        position={[-65.551, 4.828, 18.469]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["10202_(Layer_0)129"].geometry}
        material={materials["Low.002"]}
        position={[-74.604, 4.771, 18.367]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["10501047"].geometry}
        material={materials["Paint Gloss Grey #1965"]}
        position={[-60.702, 6.848, 14.165]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["50002019"].geometry}
        material={materials["Paint Gloss Grey #1948"]}
        position={[-60.902, 6.859, 14.18]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["50003023"].geometry}
        material={materials["Paint Gloss Grey #1949"]}
        position={[-60.98, 6.882, 14.213]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["50005027"].geometry}
        material={materials["Paint Gloss Grey #1900"]}
        position={[-60.938, 5.639, 10.776]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["50005031"].geometry}
        material={materials["Paint Gloss Grey #1903"]}
        position={[-60.938, 5.639, 11.845]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["50005043"].geometry}
        material={materials["Paint Gloss Grey #1950"]}
        position={[-60.924, 6.863, 14.157]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["50005047"].geometry}
        material={materials["Paint Gloss Grey #1953"]}
        position={[-60.924, 6.863, 15.227]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BIT_BIT_447534_1.geometry}
        material={materials["Low.002"]}
        position={[-73.35, 5.333, 15.237]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BIT_BIT_447534_1001.geometry}
        material={materials["Low.002"]}
        position={[-73.357, 5.334, 11.65]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes[
            "Construction_Stairs-Precision_Ladders-Ships_Ladder_Cros_b7c001"
          ].geometry
        }
        material={materials["Paint Gloss Yellow #348.141"]}
        position={[-66.054, 6.727, 2.326]}
      />
      <group position={[-69.816, 5.462, 18.748]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004.geometry}
          material={materials["Low.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004_1.geometry}
          material={materials.Black}
        />
      </group>
      <group position={[-65.074, 5.616, 12.328]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube016.geometry}
          material={materials["Low.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube016_1.geometry}
          material={materials.Black}
        />
      </group>
      <group position={[-71.204, 5.259, 12.396]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube044.geometry}
          material={materials["Low.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube044_1.geometry}
          material={materials.Black}
        />
      </group>
      <group position={[-67.538, 7.644, 7.27]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder071.geometry}
          material={materials["Low.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder071_1.geometry}
          material={materials.Black}
        />
      </group>
      <group position={[-74.533, 8.403, 14.223]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder074.geometry}
          material={materials["Low.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder074_1.geometry}
          material={materials.Black}
        />
      </group>
      <group position={[-74.458, 5.492, 18.389]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder075.geometry}
          material={materials["Low.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder075_1.geometry}
          material={materials.Black}
        />
      </group>
      <group position={[-65.532, 5.662, 18.334]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder076.geometry}
          material={materials["Low.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder076_1.geometry}
          material={materials.Black}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder049.geometry}
        material={materials["Low.002"]}
        position={[-75.089, 9.022, -4.908]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder050.geometry}
        material={materials["Low.002"]}
        position={[-71.247, 9.022, -4.301]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder051.geometry}
        material={materials["Low.002"]}
        position={[-68.115, 9.022, -2.372]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder052.geometry}
        material={materials["Low.002"]}
        position={[-75.089, 9.022, 1.783]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder053.geometry}
        material={materials["Low.002"]}
        position={[-75.089, 9.022, 7.905]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder055.geometry}
        material={materials["Low.002"]}
        position={[-75.089, 9.022, 12.816]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder056.geometry}
        material={materials["Low.002"]}
        position={[-68.107, 8.604, 5.865]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder057.geometry}
        material={materials["Low.002"]}
        position={[-72.414, 9.022, 11.294]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder058.geometry}
        material={materials["Low.002"]}
        position={[-72.414, 9.022, 14.69]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder059.geometry}
        material={materials["Low.002"]}
        position={[-66.408, 8.604, 7.75]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder060.geometry}
        material={materials["Low.002"]}
        position={[-63.734, 8.511, 7.75]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder061.geometry}
        material={materials["Low.002"]}
        position={[-61.176, 8.226, 7.75]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder062.geometry}
        material={materials["Low.002"]}
        position={[-61.176, 8.226, 11.287]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder063.geometry}
        material={materials["Low.002"]}
        position={[-61.176, 8.226, 14.698]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder064.geometry}
        material={materials["Low.002"]}
        position={[-63.734, 8.511, 11.246]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder065.geometry}
        material={materials["Low.002"]}
        position={[-63.734, 8.511, 14.705]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder066.geometry}
        material={materials["Low.002"]}
        position={[-66.408, 8.604, 11.261]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder067.geometry}
        material={materials["Low.002"]}
        position={[-66.408, 8.604, 14.702]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Escalera_ensamblada_Escalera_1239256002.geometry}
        material={materials["Paint Matte Grey #1.006"]}
        position={[-69.879, 5.837, 1.821]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Escalera_ensamblada_Escalera_1248001_1001.geometry}
        material={materials["Paint Matte Grey #43"]}
        position={[-76.12, 7.454, 6.233]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Escalera_ensamblada_Escalera_1248001_1002.geometry}
        material={materials["Paint Matte Grey #38"]}
        position={[-73.805, 7.418, -2.829]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Escalera_ensamblada_Escalera_1248001_1003.geometry}
        material={materials["Paint Matte Grey #36"]}
        position={[-69.488, 7.767, -3.358]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Escalera_ensamblada_Escalera_1248001_1004.geometry}
        material={materials["Paint Matte Grey #42"]}
        position={[-67.051, 7.767, -3.358]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Escalera_ensamblada_Escalera_1248001_1005.geometry}
        material={materials["Paint Matte Grey #41"]}
        position={[-67.051, 7.418, -2.829]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Escalera_ensamblada_Escalera_1248001_1006.geometry}
        material={materials["Paint Matte Grey #37"]}
        position={[-73.805, 7.767, -3.358]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Escalera_ensamblada_Escalera_1248001_1007.geometry}
        material={materials["Paint Matte Grey #35"]}
        position={[-69.488, 7.418, -2.829]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Escalera_ensamblada_Escalera_1248001_1008.geometry}
        material={materials["Paint Matte Grey #39"]}
        position={[-76.12, 7.873, -3.358]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes.Gravedad_Horizontar_Gravedad_Horizontal_460344001.geometry
        }
        material={materials["Low.002"]}
        position={[-74.994, 5.433, 9.371]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Motor_eje_40mm_8in_(Layer_0)019"].geometry}
        material={nodes["Motor_eje_40mm_8in_(Layer_0)019"].material}
        position={[-14.714, 4.774, -7.18]}
        rotation={[0, 1.571, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Motor_eje_40mm_8in_(Layer_0)020"].geometry}
        material={nodes["Motor_eje_40mm_8in_(Layer_0)020"].material}
        position={[-14.714, 4.774, -7.18]}
        rotation={[0, 1.571, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Motor_eje_40mm_8in_(Layer_0)021"].geometry}
        material={nodes["Motor_eje_40mm_8in_(Layer_0)021"].material}
        position={[-14.714, 4.774, -7.18]}
        rotation={[0, 1.571, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.paso_hombre_Crossover_1291613002.geometry}
        material={materials["Paint Gloss Yellow #348.140"]}
        position={[-65.004, 8.416, 14.469]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.paso_hombre_Crossover_1291633002.geometry}
        material={materials["Paint Gloss Yellow #348.143"]}
        position={[-65.004, 8.416, 11.059]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.paso_hombre_Crossover_1291643002.geometry}
        material={materials["Paint Gloss Yellow #348.142"]}
        position={[-65.004, 8.416, 7.512]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Suelo_Generic_Floor_-_100mm_2_1219942002"].geometry}
        material={materials["Paint Matte Grey #1.007"]}
        position={[-71.315, 7.181, 9.553]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Suelo_Generic_Floor_-_100mm_2_1219942003"].geometry}
        material={materials["METAL AMARILLO"]}
        position={[-76.609, 7.65, 9.437]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Suelo_Generic_Floor_-_100mm_2_1219942004"].geometry}
        material={materials["METAL AMARILLO"]}
        position={[-75.353, 7.632, 14.955]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Suelo_Generic_Floor_-_100mm_2_1219942005"].geometry}
        material={materials["METAL AMARILLO"]}
        position={[-68.96, 7.635, 15.994]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Suelo_Generic_Floor_-_100mm_2_1219942006"].geometry}
        material={materials["METAL AMARILLO"]}
        position={[-64.544, 7.642, 15.499]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Suelo_Generic_Floor_-_100mm_2_1219942007"].geometry}
        material={materials["METAL AMARILLO"]}
        position={[-68.622, 7.634, 13.425]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Suelo_Generic_Floor_-_100mm_2_1219942008"].geometry}
        material={materials["METAL AMARILLO"]}
        position={[-67.947, 7.637, 9.959]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Suelo_Generic_Floor_-_100mm_2_1219942009"].geometry}
        material={materials["METAL AMARILLO"]}
        position={[-71.708, 7.646, 6.451]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Suelo_Generic_Floor_-_100mm_2_1219942010"].geometry}
        material={materials["METAL AMARILLO"]}
        position={[-65.919, 7.644, 2.438]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Suelo_Generic_Floor_-_100mm_2_1219942011"].geometry}
        material={materials["METAL AMARILLO"]}
        position={[-71.185, 7.611, -1.349]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Suelo_Generic_Floor_-_100mm_2_1316463002"].geometry}
        material={materials["Paint Matte Grey #1.005"]}
        position={[-76.108, 7.681, 1.124]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes["Suelo_Generic_Floor_-_100mm_2_1316463003"].geometry}
        material={materials["METAL AMARILLO"]}
        position={[-76.597, 8.104, 1.124]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes["Símbolo_de_importación_ubicación_<No_compartido>_12_1e4006"]
            .geometry
        }
        material={materials["Low.002"]}
        position={[-62.865, 5.899, 14.862]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes["Símbolo_de_importación_ubicación_<No_compartido>_12_1e4007"]
            .geometry
        }
        material={materials["Low.002"]}
        position={[-62.865, 5.899, 11.471]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          nodes["Símbolo_de_importación_ubicación_<No_compartido>_12_1e4008"]
            .geometry
        }
        material={materials["Low.002"]}
        position={[-62.865, 5.899, 7.83]}
      />
      <group position={[-62.885, 5.658, 7.78]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh095.geometry}
          material={materials["Low.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh095_1.geometry}
          material={materials.Black}
        />
      </group>
      <group position={[-73.135, 8.439, 11.19]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh096.geometry}
          material={materials["Low.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh096_1.geometry}
          material={materials.Black}
        />
      </group>
      <group position={[-62.879, 5.658, 11.422]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh102.geometry}
          material={materials["Low.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh102_1.geometry}
          material={materials.Black}
        />
      </group>
      <group position={[-62.878, 5.658, 14.815]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh103.geometry}
          material={materials["Low.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh103_1.geometry}
          material={materials.Black}
        />
      </group>
      <group position={[-66.373, 7.62, 14.585]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh104.geometry}
          material={materials["Low.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh104_1.geometry}
          material={materials.Black}
        />
      </group>
      <group position={[-61.607, 5.818, 14.706]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh115.geometry}
          material={materials["Low.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh115_1.geometry}
          material={materials.Black}
        />
      </group>
      <group position={[-67.964, 7.983, 2.179]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh105.geometry}
          material={materials["Low.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh105_1.geometry}
          material={materials.Black}
        />
      </group>
      <group position={[-66.405, 7.622, 11.152]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh106.geometry}
          material={materials["Low.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh106_1.geometry}
          material={materials.Black}
        />
      </group>
      <group position={[-61.583, 7.111, 7.792]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh113.geometry}
          material={materials["Low.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh113_1.geometry}
          material={materials.Black}
        />
      </group>
      <group position={[-61.583, 7.111, 14.707]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh112.geometry}
          material={materials["Low.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh112_1.geometry}
          material={materials.Black}
        />
      </group>
      <group position={[-61.607, 5.818, 11.298]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh116.geometry}
          material={materials["Low.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh116_1.geometry}
          material={materials.Black}
        />
      </group>
      <group position={[-71.039, 6.688, 2.207]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh107.geometry}
          material={materials["Low.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh107_1.geometry}
          material={materials.Black}
        />
      </group>
      <group position={[-63.819, 7.291, 7.744]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh108.geometry}
          material={materials["Low.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh108_1.geometry}
          material={materials.Black}
        />
      </group>
      <group position={[-61.607, 5.818, 7.734]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh117.geometry}
          material={materials["Low.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh117_1.geometry}
          material={materials.Black}
        />
      </group>
      <group position={[-74.949, 8.383, 5.8]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh109.geometry}
          material={materials["Low.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh109_1.geometry}
          material={materials.Black}
        />
      </group>
      <group position={[-75.066, 5.424, 16.599]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh110.geometry}
          material={materials["Low.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh110_1.geometry}
          material={materials.Black}
        />
      </group>
      <group position={[-75.085, 5.419, 13.163]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh111.geometry}
          material={materials["Low.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh111_1.geometry}
          material={materials.Black}
        />
      </group>
      <group position={[-61.583, 7.111, 11.28]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh114.geometry}
          material={materials["Low.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh114_1.geometry}
          material={materials.Black}
        />
      </group>
      <group position={[-72.983, 8.5, 14.706]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh136.geometry}
          material={materials["Low.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh136_1.geometry}
          material={materials.Black}
        />
      </group>
      <group position={[-75.182, 5.51, 11.055]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh137.geometry}
          material={materials["Low.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh137_1.geometry}
          material={materials.Black}
        />
      </group>
      <group position={[-75.182, 5.51, 14.703]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh144.geometry}
          material={materials["Low.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh144_1.geometry}
          material={materials.Black}
        />
      </group>
      <group position={[-63.637, 5.644, 8.502]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh126.geometry}
          material={materials["Low.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh126_1.geometry}
          material={materials.Black}
        />
      </group>
      <group position={[-73.796, 8.369, 10.641]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh127.geometry}
          material={materials["Low.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh127_1.geometry}
          material={materials.Black}
        />
      </group>
      <group position={[-63.637, 5.644, 12.136]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh128.geometry}
          material={materials["Low.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh128_1.geometry}
          material={materials.Black}
        />
      </group>
      <group position={[-63.631, 5.643, 15.539]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh129.geometry}
          material={materials["Low.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mesh129_1.geometry}
          material={materials.Black}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/cvracentrado.glb");
