/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function CVRAModel(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/cvra.glb");
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group
          name="62001_(Layer_0)005"
          position={[-6.201, 7.868, -1.652]}
          rotation={[0.019, 0, 0]}
        />
        <group
          name="62001_(Layer_0)001"
          position={[-4.236, -0.01, -21.774]}
          rotation={[0, 0.791, 0]}
        />
        <group name="62001_(Layer_0)002" />
        <group name="62001_(Layer_0)003" position={[-7.75, 0, -9.769]} />
        <group name="62001_(Layer_0)004" position={[-26.676, 7.907, -10.288]} />
        <mesh
          name="Motor_eje_40mm_8in_(Layer_0)019"
          castShadow
          receiveShadow
          geometry={nodes["Motor_eje_40mm_8in_(Layer_0)019"].geometry}
          material={nodes["Motor_eje_40mm_8in_(Layer_0)019"].material}
          position={[-14.714, 4.774, -7.18]}
          rotation={[0, 1.571, 0]}
        />
        <mesh
          name="Motor_eje_40mm_8in_(Layer_0)020"
          castShadow
          receiveShadow
          geometry={nodes["Motor_eje_40mm_8in_(Layer_0)020"].geometry}
          material={nodes["Motor_eje_40mm_8in_(Layer_0)020"].material}
          position={[-14.714, 4.774, -7.18]}
          rotation={[0, 1.571, 0]}
        />
        <mesh
          name="Motor_eje_40mm_8in_(Layer_0)021"
          castShadow
          receiveShadow
          geometry={nodes["Motor_eje_40mm_8in_(Layer_0)021"].geometry}
          material={nodes["Motor_eje_40mm_8in_(Layer_0)021"].material}
          position={[-14.714, 4.774, -7.18]}
          rotation={[0, 1.571, 0]}
        />
        <group
          name="Handle_Cube002"
          position={[5.129, 10.723, 2.031]}
          rotation={[2.854, 0, -3.127]}
        />
        <group
          name="Armature004"
          position={[1.949, 10.762, 1.912]}
          scale={0.534}
        >
          <skinnedMesh
            name="maleta_naranjada"
            geometry={nodes.maleta_naranjada.geometry}
            material={materials.Material}
            skeleton={nodes.maleta_naranjada.skeleton}
          />
          <primitive object={nodes.Bone} />
        </group>
        <group
          name="Armature005"
          position={[-28.158, 10.762, 1.651]}
          scale={0.534}
        >
          <skinnedMesh
            name="Cube014"
            geometry={nodes.Cube014.geometry}
            material={materials["maleta roja"]}
            skeleton={nodes.Cube014.skeleton}
          />
          <primitive object={nodes.Bone_1} />
        </group>
        <mesh
          name="paso_hombre_Crossover_1291613002"
          castShadow
          receiveShadow
          geometry={nodes.paso_hombre_Crossover_1291613002.geometry}
          material={materials["Paint Gloss Yellow #348.140"]}
          position={[0, 0, 11.814]}
        />
        <mesh
          name="Construction_Stairs-Precision_Ladders-Ships_Ladder_Cros_b7c001"
          castShadow
          receiveShadow
          geometry={
            nodes[
              "Construction_Stairs-Precision_Ladders-Ships_Ladder_Cros_b7c001"
            ].geometry
          }
          material={materials["Paint Gloss Yellow #348.141"]}
          position={[0, 0, 11.814]}
        />
        <mesh
          name="paso_hombre_Crossover_1291643002"
          castShadow
          receiveShadow
          geometry={nodes.paso_hombre_Crossover_1291643002.geometry}
          material={materials["Paint Gloss Yellow #348.142"]}
          position={[0, 0, 11.814]}
        />
        <mesh
          name="paso_hombre_Crossover_1291633002"
          castShadow
          receiveShadow
          geometry={nodes.paso_hombre_Crossover_1291633002.geometry}
          material={materials["Paint Gloss Yellow #348.143"]}
          position={[0, 0, 11.814]}
        />
        <mesh
          name="Suelo_Generic_Floor_-_100mm_2_1316463002"
          castShadow
          receiveShadow
          geometry={nodes["Suelo_Generic_Floor_-_100mm_2_1316463002"].geometry}
          material={materials["Paint Matte Grey #1.005"]}
          position={[0, 0, 11.814]}
        />
        <mesh
          name="Escalera_ensamblada_Escalera_1248001_1001"
          castShadow
          receiveShadow
          geometry={nodes.Escalera_ensamblada_Escalera_1248001_1001.geometry}
          material={materials["Paint Matte Grey #43"]}
          position={[0, 0, 11.814]}
        />
        <mesh
          name="Escalera_ensamblada_Escalera_1239256002"
          castShadow
          receiveShadow
          geometry={nodes.Escalera_ensamblada_Escalera_1239256002.geometry}
          material={materials["Paint Matte Grey #1.006"]}
          position={[0, 0, 11.814]}
        />
        <mesh
          name="Escalera_ensamblada_Escalera_1248001_1002"
          castShadow
          receiveShadow
          geometry={nodes.Escalera_ensamblada_Escalera_1248001_1002.geometry}
          material={materials["Paint Matte Grey #38"]}
          position={[0, 0, 11.814]}
        />
        <mesh
          name="Escalera_ensamblada_Escalera_1248001_1003"
          castShadow
          receiveShadow
          geometry={nodes.Escalera_ensamblada_Escalera_1248001_1003.geometry}
          material={materials["Paint Matte Grey #36"]}
          position={[0, 0, 11.814]}
        />
        <mesh
          name="Escalera_ensamblada_Escalera_1248001_1004"
          castShadow
          receiveShadow
          geometry={nodes.Escalera_ensamblada_Escalera_1248001_1004.geometry}
          material={materials["Paint Matte Grey #42"]}
          position={[0, 0, 11.814]}
        />
        <mesh
          name="Escalera_ensamblada_Escalera_1248001_1005"
          castShadow
          receiveShadow
          geometry={nodes.Escalera_ensamblada_Escalera_1248001_1005.geometry}
          material={materials["Paint Matte Grey #41"]}
          position={[0, 0, 11.814]}
        />
        <mesh
          name="Suelo_Generic_Floor_-_100mm_2_1219942002"
          castShadow
          receiveShadow
          geometry={nodes["Suelo_Generic_Floor_-_100mm_2_1219942002"].geometry}
          material={materials["Paint Matte Grey #1.007"]}
          position={[0, 0, 11.814]}
        />
        <mesh
          name="Escalera_ensamblada_Escalera_1248001_1006"
          castShadow
          receiveShadow
          geometry={nodes.Escalera_ensamblada_Escalera_1248001_1006.geometry}
          material={materials["Paint Matte Grey #37"]}
          position={[0, 0, 11.814]}
        />
        <mesh
          name="Escalera_ensamblada_Escalera_1248001_1007"
          castShadow
          receiveShadow
          geometry={nodes.Escalera_ensamblada_Escalera_1248001_1007.geometry}
          material={materials["Paint Matte Grey #35"]}
          position={[0, 0, 11.814]}
        />
        <mesh
          name="Escalera_ensamblada_Escalera_1248001_1008"
          castShadow
          receiveShadow
          geometry={nodes.Escalera_ensamblada_Escalera_1248001_1008.geometry}
          material={materials["Paint Matte Grey #39"]}
          position={[0, 0, 11.814]}
        />
        <mesh
          name="Suelo_Generic_Floor_-_100mm_2_1316463003"
          castShadow
          receiveShadow
          geometry={nodes["Suelo_Generic_Floor_-_100mm_2_1316463003"].geometry}
          material={materials["METAL AMARILLO"]}
          position={[0, 0, 11.814]}
        />
        <mesh
          name="Suelo_Generic_Floor_-_100mm_2_1219942003"
          castShadow
          receiveShadow
          geometry={nodes["Suelo_Generic_Floor_-_100mm_2_1219942003"].geometry}
          material={materials["METAL AMARILLO"]}
          position={[0, 0, 11.814]}
        />
        <mesh
          name="Suelo_Generic_Floor_-_100mm_2_1219942004"
          castShadow
          receiveShadow
          geometry={nodes["Suelo_Generic_Floor_-_100mm_2_1219942004"].geometry}
          material={materials["METAL AMARILLO"]}
          position={[0, -0.019, 11.814]}
        />
        <mesh
          name="Suelo_Generic_Floor_-_100mm_2_1219942005"
          castShadow
          receiveShadow
          geometry={nodes["Suelo_Generic_Floor_-_100mm_2_1219942005"].geometry}
          material={materials["METAL AMARILLO"]}
          position={[0, 0, 11.814]}
        />
        <mesh
          name="Suelo_Generic_Floor_-_100mm_2_1219942006"
          castShadow
          receiveShadow
          geometry={nodes["Suelo_Generic_Floor_-_100mm_2_1219942006"].geometry}
          material={materials["METAL AMARILLO"]}
          position={[0, 0, 11.814]}
        />
        <mesh
          name="Suelo_Generic_Floor_-_100mm_2_1219942007"
          castShadow
          receiveShadow
          geometry={nodes["Suelo_Generic_Floor_-_100mm_2_1219942007"].geometry}
          material={materials["METAL AMARILLO"]}
          position={[0, 0, 11.814]}
        />
        <mesh
          name="Suelo_Generic_Floor_-_100mm_2_1219942008"
          castShadow
          receiveShadow
          geometry={nodes["Suelo_Generic_Floor_-_100mm_2_1219942008"].geometry}
          material={materials["METAL AMARILLO"]}
          position={[0, 0, 11.814]}
        />
        <mesh
          name="Suelo_Generic_Floor_-_100mm_2_1219942009"
          castShadow
          receiveShadow
          geometry={nodes["Suelo_Generic_Floor_-_100mm_2_1219942009"].geometry}
          material={materials["METAL AMARILLO"]}
          position={[0, 0, 11.814]}
        />
        <mesh
          name="Suelo_Generic_Floor_-_100mm_2_1219942010"
          castShadow
          receiveShadow
          geometry={nodes["Suelo_Generic_Floor_-_100mm_2_1219942010"].geometry}
          material={materials["METAL AMARILLO"]}
          position={[0, 0, 11.814]}
        />
        <mesh
          name="Suelo_Generic_Floor_-_100mm_2_1219942011"
          castShadow
          receiveShadow
          geometry={nodes["Suelo_Generic_Floor_-_100mm_2_1219942011"].geometry}
          material={materials["METAL AMARILLO"]}
          position={[0, 0, 11.814]}
        />
        <group name="Suelo_Generic_Floor_-_100mm_2_1217029_1010" />
        <mesh
          name="10202_(Layer_0)065"
          castShadow
          receiveShadow
          geometry={nodes["10202_(Layer_0)065"].geometry}
          material={materials["Low.002"]}
          position={[0, 0, 12.05]}
        />
        <mesh
          name="10202_(Layer_0)066"
          castShadow
          receiveShadow
          geometry={nodes["10202_(Layer_0)066"].geometry}
          material={materials["Low.002"]}
          position={[0, 0, 12.05]}
        />
        <mesh
          name="10202_(Layer_0)067"
          castShadow
          receiveShadow
          geometry={nodes["10202_(Layer_0)067"].geometry}
          material={materials["Low.002"]}
          position={[0, 0, 12.05]}
        />
        <mesh
          name="10202_(Layer_0)068"
          castShadow
          receiveShadow
          geometry={nodes["10202_(Layer_0)068"].geometry}
          material={materials["Low.002"]}
          position={[0, 0, 12.05]}
        />
        <mesh
          name="10202_(Layer_0)069"
          castShadow
          receiveShadow
          geometry={nodes["10202_(Layer_0)069"].geometry}
          material={materials["Low.002"]}
          position={[0, 0, 12.05]}
        />
        <mesh
          name="10202_(Layer_0)070"
          castShadow
          receiveShadow
          geometry={nodes["10202_(Layer_0)070"].geometry}
          material={materials["Low.002"]}
          position={[0, 0, 12.05]}
        />
        <mesh
          name="10202_(Layer_0)071"
          castShadow
          receiveShadow
          geometry={nodes["10202_(Layer_0)071"].geometry}
          material={materials["Low.002"]}
          position={[0, 0, 12.05]}
        />
        <mesh
          name="10202_(Layer_0)072"
          castShadow
          receiveShadow
          geometry={nodes["10202_(Layer_0)072"].geometry}
          material={materials["Low.002"]}
          position={[0, 0, 12.05]}
        />
        <mesh
          name="10202_(Layer_0)073"
          castShadow
          receiveShadow
          geometry={nodes["10202_(Layer_0)073"].geometry}
          material={materials["Low.002"]}
          position={[0, 0, 12.05]}
        />
        <mesh
          name="10202_(Layer_0)074"
          castShadow
          receiveShadow
          geometry={nodes["10202_(Layer_0)074"].geometry}
          material={materials["Low.002"]}
          position={[0, 0, 12.05]}
        />
        <mesh
          name="10202_(Layer_0)105"
          castShadow
          receiveShadow
          geometry={nodes["10202_(Layer_0)105"].geometry}
          material={materials["Low.002"]}
          position={[0, 0, 12.05]}
        />
        <mesh
          name="10202_(Layer_0)106"
          castShadow
          receiveShadow
          geometry={nodes["10202_(Layer_0)106"].geometry}
          material={materials["Low.002"]}
          position={[0, 0, 12.05]}
        />
        <mesh
          name="10202_(Layer_0)107"
          castShadow
          receiveShadow
          geometry={nodes["10202_(Layer_0)107"].geometry}
          material={materials["Low.002"]}
          position={[0, 0, 12.05]}
        />
        <mesh
          name="10202_(Layer_0)108"
          castShadow
          receiveShadow
          geometry={nodes["10202_(Layer_0)108"].geometry}
          material={materials["Low.002"]}
          position={[0, 0, 12.05]}
        />
        <mesh
          name="10202_(Layer_0)109"
          castShadow
          receiveShadow
          geometry={nodes["10202_(Layer_0)109"].geometry}
          material={materials["Low.002"]}
          position={[0, 0, 12.05]}
        />
        <mesh
          name="10202_(Layer_0)110"
          castShadow
          receiveShadow
          geometry={nodes["10202_(Layer_0)110"].geometry}
          material={materials["Low.002"]}
          position={[0, 0, 12.05]}
        />
        <mesh
          name="10202_(Layer_0)111"
          castShadow
          receiveShadow
          geometry={nodes["10202_(Layer_0)111"].geometry}
          material={materials["Low.002"]}
          position={[0, 0, 12.05]}
        />
        <mesh
          name="10202_(Layer_0)112"
          castShadow
          receiveShadow
          geometry={nodes["10202_(Layer_0)112"].geometry}
          material={materials["Low.002"]}
          position={[0, 0, 12.05]}
        />
        <mesh
          name="10202_(Layer_0)113"
          castShadow
          receiveShadow
          geometry={nodes["10202_(Layer_0)113"].geometry}
          material={materials["Low.002"]}
          position={[0, 0, 12.05]}
        />
        <mesh
          name="10202_(Layer_0)114"
          castShadow
          receiveShadow
          geometry={nodes["10202_(Layer_0)114"].geometry}
          material={materials["Low.002"]}
          position={[0, 0, 12.05]}
        />
        <mesh
          name="10202_(Layer_0)115"
          castShadow
          receiveShadow
          geometry={nodes["10202_(Layer_0)115"].geometry}
          material={materials["Low.002"]}
          position={[0, 0, 12.05]}
        />
        <mesh
          name="10202_(Layer_0)116"
          castShadow
          receiveShadow
          geometry={nodes["10202_(Layer_0)116"].geometry}
          material={materials["Low.002"]}
          position={[0, 0, 12.05]}
        />
        <mesh
          name="10202_(Layer_0)117"
          castShadow
          receiveShadow
          geometry={nodes["10202_(Layer_0)117"].geometry}
          material={materials["Low.002"]}
          position={[0, 0, 12.05]}
        />
        <mesh
          name="10202_(Layer_0)118"
          castShadow
          receiveShadow
          geometry={nodes["10202_(Layer_0)118"].geometry}
          material={materials["Low.002"]}
          position={[0, 0, 12.05]}
        />
        <mesh
          name="10202_(Layer_0)119"
          castShadow
          receiveShadow
          geometry={nodes["10202_(Layer_0)119"].geometry}
          material={materials["Low.002"]}
          position={[0, 0, 12.05]}
        />
        <mesh
          name="10202_(Layer_0)120"
          castShadow
          receiveShadow
          geometry={nodes["10202_(Layer_0)120"].geometry}
          material={materials["Low.002"]}
          position={[0, 0, 12.05]}
        />
        <mesh
          name="10202_(Layer_0)121"
          castShadow
          receiveShadow
          geometry={nodes["10202_(Layer_0)121"].geometry}
          material={materials["Low.002"]}
          position={[0, 0, 12.05]}
        />
        <mesh
          name="10202_(Layer_0)122"
          castShadow
          receiveShadow
          geometry={nodes["10202_(Layer_0)122"].geometry}
          material={materials["Low.002"]}
          position={[0, 0, 12.05]}
        />
        <mesh
          name="10202_(Layer_0)123"
          castShadow
          receiveShadow
          geometry={nodes["10202_(Layer_0)123"].geometry}
          material={materials["Low.002"]}
          position={[0, 0, 12.05]}
        />
        <mesh
          name="10202_(Layer_0)124"
          castShadow
          receiveShadow
          geometry={nodes["10202_(Layer_0)124"].geometry}
          material={materials["Low.002"]}
          position={[0, 0, 12.05]}
        />
        <mesh
          name="10202_(Layer_0)125"
          castShadow
          receiveShadow
          geometry={nodes["10202_(Layer_0)125"].geometry}
          material={materials["Low.002"]}
          position={[0, 0, 12.05]}
        />
        <mesh
          name="10202_(Layer_0)126"
          castShadow
          receiveShadow
          geometry={nodes["10202_(Layer_0)126"].geometry}
          material={materials["Low.002"]}
          position={[0, 0, 12.05]}
        />
        <mesh
          name="10202_(Layer_0)127"
          castShadow
          receiveShadow
          geometry={nodes["10202_(Layer_0)127"].geometry}
          material={materials["Low.002"]}
          position={[0, 0, 12.05]}
        />
        <mesh
          name="10202_(Layer_0)128"
          castShadow
          receiveShadow
          geometry={nodes["10202_(Layer_0)128"].geometry}
          material={materials["Low.002"]}
          position={[0, 0, 12.05]}
        />
        <mesh
          name="10202_(Layer_0)129"
          castShadow
          receiveShadow
          geometry={nodes["10202_(Layer_0)129"].geometry}
          material={materials["Low.002"]}
          position={[0, 0, 12.05]}
        />
        <mesh
          name="BIT_BIT_447534_1"
          castShadow
          receiveShadow
          geometry={nodes.BIT_BIT_447534_1.geometry}
          material={materials["Low.002"]}
          position={[0, 0, 12.05]}
        />
        <mesh
          name="BIT_BIT_447534_1001"
          castShadow
          receiveShadow
          geometry={nodes.BIT_BIT_447534_1001.geometry}
          material={materials["Low.002"]}
          position={[0, 0, 12.05]}
        />
        <group name="Cube015" position={[0, 0, 12.05]}>
          <mesh
            name="Cube004"
            castShadow
            receiveShadow
            geometry={nodes.Cube004.geometry}
            material={materials["Low.002"]}
          />
          <mesh
            name="Cube004_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube004_1.geometry}
            material={materials.Black}
          />
        </group>
        <group name="Cube018" position={[0, 0, 12.05]}>
          <mesh
            name="Cube016"
            castShadow
            receiveShadow
            geometry={nodes.Cube016.geometry}
            material={materials["Low.002"]}
          />
          <mesh
            name="Cube016_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube016_1.geometry}
            material={materials.Black}
          />
        </group>
        <group name="Cube019" position={[0, 0, 12.05]}>
          <mesh
            name="Cube044"
            castShadow
            receiveShadow
            geometry={nodes.Cube044.geometry}
            material={materials["Low.002"]}
          />
          <mesh
            name="Cube044_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube044_1.geometry}
            material={materials.Black}
          />
        </group>
        <group name="Cylinder044" position={[0, 0, 12.05]}>
          <mesh
            name="Cylinder071"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder071.geometry}
            material={materials["Low.002"]}
          />
          <mesh
            name="Cylinder071_1"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder071_1.geometry}
            material={materials.Black}
          />
        </group>
        <group name="Cylinder045" position={[0, 0, 12.05]}>
          <mesh
            name="Cylinder074"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder074.geometry}
            material={materials["Low.002"]}
          />
          <mesh
            name="Cylinder074_1"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder074_1.geometry}
            material={materials.Black}
          />
        </group>
        <group name="Cylinder046" position={[0, 0, 12.05]}>
          <mesh
            name="Cylinder075"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder075.geometry}
            material={materials["Low.002"]}
          />
          <mesh
            name="Cylinder075_1"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder075_1.geometry}
            material={materials.Black}
          />
        </group>
        <group name="Cylinder047" position={[0, 0, 12.05]}>
          <mesh
            name="Cylinder076"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder076.geometry}
            material={materials["Low.002"]}
          />
          <mesh
            name="Cylinder076_1"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder076_1.geometry}
            material={materials.Black}
          />
        </group>
        <mesh
          name="Cylinder049"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder049.geometry}
          material={materials["Low.002"]}
          position={[0, 0, 12.05]}
        />
        <mesh
          name="Cylinder050"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder050.geometry}
          material={materials["Low.002"]}
          position={[0, 0, 12.05]}
        />
        <mesh
          name="Cylinder051"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder051.geometry}
          material={materials["Low.002"]}
          position={[0, 0, 12.05]}
        />
        <mesh
          name="Cylinder052"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder052.geometry}
          material={materials["Low.002"]}
          position={[0, 0, 12.05]}
        />
        <mesh
          name="Cylinder053"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder053.geometry}
          material={materials["Low.002"]}
          position={[0, 0, 12.05]}
        />
        <mesh
          name="Cylinder055"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder055.geometry}
          material={materials["Low.002"]}
          position={[0, 0, 12.05]}
        />
        <mesh
          name="Cylinder056"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder056.geometry}
          material={materials["Low.002"]}
          position={[0, 0, 12.05]}
        />
        <mesh
          name="Cylinder057"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder057.geometry}
          material={materials["Low.002"]}
          position={[0, 0, 12.05]}
        />
        <mesh
          name="Cylinder058"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder058.geometry}
          material={materials["Low.002"]}
          position={[0, 0, 12.05]}
        />
        <mesh
          name="Cylinder059"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder059.geometry}
          material={materials["Low.002"]}
          position={[0, 0, 12.05]}
        />
        <mesh
          name="Cylinder060"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder060.geometry}
          material={materials["Low.002"]}
          position={[0, 0, 12.05]}
        />
        <mesh
          name="Cylinder061"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder061.geometry}
          material={materials["Low.002"]}
          position={[0, 0, 12.05]}
        />
        <mesh
          name="Cylinder062"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder062.geometry}
          material={materials["Low.002"]}
          position={[0, 0, 12.05]}
        />
        <mesh
          name="Cylinder063"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder063.geometry}
          material={materials["Low.002"]}
          position={[0, 0, 12.05]}
        />
        <mesh
          name="Cylinder064"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder064.geometry}
          material={materials["Low.002"]}
          position={[0, 0, 12.05]}
        />
        <mesh
          name="Cylinder065"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder065.geometry}
          material={materials["Low.002"]}
          position={[0, 0, 12.05]}
        />
        <mesh
          name="Cylinder066"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder066.geometry}
          material={materials["Low.002"]}
          position={[0, 0, 12.05]}
        />
        <mesh
          name="Cylinder067"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder067.geometry}
          material={materials["Low.002"]}
          position={[0, 0, 12.05]}
        />
        <mesh
          name="Gravedad_Horizontar_Gravedad_Horizontal_460344001"
          castShadow
          receiveShadow
          geometry={
            nodes.Gravedad_Horizontar_Gravedad_Horizontal_460344001.geometry
          }
          material={materials["Low.002"]}
          position={[0, 0, 12.05]}
        />
        <group
          name="Símbolo_de_importación_ubicación_<No_compartido>_12_1e4010"
          position={[0, 0, 12.05]}
        >
          <mesh
            name="mesh095"
            castShadow
            receiveShadow
            geometry={nodes.mesh095.geometry}
            material={materials["Low.002"]}
          />
          <mesh
            name="mesh095_1"
            castShadow
            receiveShadow
            geometry={nodes.mesh095_1.geometry}
            material={materials.Black}
          />
        </group>
        <group
          name="Símbolo_de_importación_ubicación_<No_compartido>_12_1e4011"
          position={[0, 0, 12.05]}
        >
          <mesh
            name="mesh096"
            castShadow
            receiveShadow
            geometry={nodes.mesh096.geometry}
            material={materials["Low.002"]}
          />
          <mesh
            name="mesh096_1"
            castShadow
            receiveShadow
            geometry={nodes.mesh096_1.geometry}
            material={materials.Black}
          />
        </group>
        <group
          name="Símbolo_de_importación_ubicación_<No_compartido>_12_1e4012"
          position={[0, 0, 12.05]}
        >
          <mesh
            name="mesh102"
            castShadow
            receiveShadow
            geometry={nodes.mesh102.geometry}
            material={materials["Low.002"]}
          />
          <mesh
            name="mesh102_1"
            castShadow
            receiveShadow
            geometry={nodes.mesh102_1.geometry}
            material={materials.Black}
          />
        </group>
        <group
          name="Símbolo_de_importación_ubicación_<No_compartido>_12_1e4013"
          position={[0, 0, 12.05]}
        >
          <mesh
            name="mesh103"
            castShadow
            receiveShadow
            geometry={nodes.mesh103.geometry}
            material={materials["Low.002"]}
          />
          <mesh
            name="mesh103_1"
            castShadow
            receiveShadow
            geometry={nodes.mesh103_1.geometry}
            material={materials.Black}
          />
        </group>
        <group
          name="Símbolo_de_importación_ubicación_<No_compartido>_12_31b001"
          position={[0, 0, 12.05]}
        >
          <mesh
            name="mesh104"
            castShadow
            receiveShadow
            geometry={nodes.mesh104.geometry}
            material={materials["Low.002"]}
          />
          <mesh
            name="mesh104_1"
            castShadow
            receiveShadow
            geometry={nodes.mesh104_1.geometry}
            material={materials.Black}
          />
        </group>
        <group
          name="Símbolo_de_importación_ubicación_<No_compartido>_12_31b008"
          position={[0, 0, 12.05]}
        >
          <mesh
            name="mesh115"
            castShadow
            receiveShadow
            geometry={nodes.mesh115.geometry}
            material={materials["Low.002"]}
          />
          <mesh
            name="mesh115_1"
            castShadow
            receiveShadow
            geometry={nodes.mesh115_1.geometry}
            material={materials.Black}
          />
        </group>
        <group
          name="Símbolo_de_importación_ubicación_<No_compartido>_12_31b011"
          position={[0, 0, 12.05]}
        >
          <mesh
            name="mesh105"
            castShadow
            receiveShadow
            geometry={nodes.mesh105.geometry}
            material={materials["Low.002"]}
          />
          <mesh
            name="mesh105_1"
            castShadow
            receiveShadow
            geometry={nodes.mesh105_1.geometry}
            material={materials.Black}
          />
        </group>
        <group
          name="Símbolo_de_importación_ubicación_<No_compartido>_12_31b015"
          position={[0, 0, 12.05]}
        >
          <mesh
            name="mesh106"
            castShadow
            receiveShadow
            geometry={nodes.mesh106.geometry}
            material={materials["Low.002"]}
          />
          <mesh
            name="mesh106_1"
            castShadow
            receiveShadow
            geometry={nodes.mesh106_1.geometry}
            material={materials.Black}
          />
        </group>
        <group
          name="Símbolo_de_importación_ubicación_<No_compartido>_12_31b017"
          position={[0, 0, 12.05]}
        >
          <mesh
            name="mesh113"
            castShadow
            receiveShadow
            geometry={nodes.mesh113.geometry}
            material={materials["Low.002"]}
          />
          <mesh
            name="mesh113_1"
            castShadow
            receiveShadow
            geometry={nodes.mesh113_1.geometry}
            material={materials.Black}
          />
        </group>
        <group
          name="Símbolo_de_importación_ubicación_<No_compartido>_12_31b021"
          position={[0, 0, 12.05]}
        >
          <mesh
            name="mesh112"
            castShadow
            receiveShadow
            geometry={nodes.mesh112.geometry}
            material={materials["Low.002"]}
          />
          <mesh
            name="mesh112_1"
            castShadow
            receiveShadow
            geometry={nodes.mesh112_1.geometry}
            material={materials.Black}
          />
        </group>
        <group
          name="Símbolo_de_importación_ubicación_<No_compartido>_12_31b031"
          position={[0, 0, 12.05]}
        >
          <mesh
            name="mesh116"
            castShadow
            receiveShadow
            geometry={nodes.mesh116.geometry}
            material={materials["Low.002"]}
          />
          <mesh
            name="mesh116_1"
            castShadow
            receiveShadow
            geometry={nodes.mesh116_1.geometry}
            material={materials.Black}
          />
        </group>
        <group
          name="Símbolo_de_importación_ubicación_<No_compartido>_12_31b040"
          position={[0, 0, 12.05]}
        >
          <mesh
            name="mesh107"
            castShadow
            receiveShadow
            geometry={nodes.mesh107.geometry}
            material={materials["Low.002"]}
          />
          <mesh
            name="mesh107_1"
            castShadow
            receiveShadow
            geometry={nodes.mesh107_1.geometry}
            material={materials.Black}
          />
        </group>
        <group
          name="Símbolo_de_importación_ubicación_<No_compartido>_12_31b048"
          position={[0, 0, 12.05]}
        >
          <mesh
            name="mesh108"
            castShadow
            receiveShadow
            geometry={nodes.mesh108.geometry}
            material={materials["Low.002"]}
          />
          <mesh
            name="mesh108_1"
            castShadow
            receiveShadow
            geometry={nodes.mesh108_1.geometry}
            material={materials.Black}
          />
        </group>
        <group
          name="Símbolo_de_importación_ubicación_<No_compartido>_12_31b052"
          position={[0, 0, 12.05]}
        >
          <mesh
            name="mesh117"
            castShadow
            receiveShadow
            geometry={nodes.mesh117.geometry}
            material={materials["Low.002"]}
          />
          <mesh
            name="mesh117_1"
            castShadow
            receiveShadow
            geometry={nodes.mesh117_1.geometry}
            material={materials.Black}
          />
        </group>
        <group
          name="Símbolo_de_importación_ubicación_<No_compartido>_12_31b059"
          position={[0, 0, 12.05]}
        >
          <mesh
            name="mesh109"
            castShadow
            receiveShadow
            geometry={nodes.mesh109.geometry}
            material={materials["Low.002"]}
          />
          <mesh
            name="mesh109_1"
            castShadow
            receiveShadow
            geometry={nodes.mesh109_1.geometry}
            material={materials.Black}
          />
        </group>
        <group
          name="Símbolo_de_importación_ubicación_<No_compartido>_12_31b060"
          position={[0, 0, 12.05]}
        >
          <mesh
            name="mesh110"
            castShadow
            receiveShadow
            geometry={nodes.mesh110.geometry}
            material={materials["Low.002"]}
          />
          <mesh
            name="mesh110_1"
            castShadow
            receiveShadow
            geometry={nodes.mesh110_1.geometry}
            material={materials.Black}
          />
        </group>
        <group
          name="Símbolo_de_importación_ubicación_<No_compartido>_12_31b061"
          position={[0, 0, 12.05]}
        >
          <mesh
            name="mesh111"
            castShadow
            receiveShadow
            geometry={nodes.mesh111.geometry}
            material={materials["Low.002"]}
          />
          <mesh
            name="mesh111_1"
            castShadow
            receiveShadow
            geometry={nodes.mesh111_1.geometry}
            material={materials.Black}
          />
        </group>
        <group
          name="Símbolo_de_importación_ubicación_<No_compartido>_12_31b062"
          position={[0, 0, 12.05]}
        >
          <mesh
            name="mesh114"
            castShadow
            receiveShadow
            geometry={nodes.mesh114.geometry}
            material={materials["Low.002"]}
          />
          <mesh
            name="mesh114_1"
            castShadow
            receiveShadow
            geometry={nodes.mesh114_1.geometry}
            material={materials.Black}
          />
        </group>
        <group
          name="Símbolo_de_importación_ubicación_<No_compartido>_12_31b072"
          position={[0, 0, 12.05]}
        >
          <mesh
            name="mesh136"
            castShadow
            receiveShadow
            geometry={nodes.mesh136.geometry}
            material={materials["Low.002"]}
          />
          <mesh
            name="mesh136_1"
            castShadow
            receiveShadow
            geometry={nodes.mesh136_1.geometry}
            material={materials.Black}
          />
        </group>
        <group
          name="Símbolo_de_importación_ubicación_<No_compartido>_12_31b073"
          position={[0, 0, 12.05]}
        >
          <mesh
            name="mesh137"
            castShadow
            receiveShadow
            geometry={nodes.mesh137.geometry}
            material={materials["Low.002"]}
          />
          <mesh
            name="mesh137_1"
            castShadow
            receiveShadow
            geometry={nodes.mesh137_1.geometry}
            material={materials.Black}
          />
        </group>
        <group
          name="Símbolo_de_importación_ubicación_<No_compartido>_12_31b074"
          position={[0, 0, 12.05]}
        >
          <mesh
            name="mesh144"
            castShadow
            receiveShadow
            geometry={nodes.mesh144.geometry}
            material={materials["Low.002"]}
          />
          <mesh
            name="mesh144_1"
            castShadow
            receiveShadow
            geometry={nodes.mesh144_1.geometry}
            material={materials.Black}
          />
        </group>
        <group
          name="Símbolo_de_importación_ubicación_<No_compartido>_12_a7a005"
          position={[0, 0, 12.05]}
        >
          <mesh
            name="mesh126"
            castShadow
            receiveShadow
            geometry={nodes.mesh126.geometry}
            material={materials["Low.002"]}
          />
          <mesh
            name="mesh126_1"
            castShadow
            receiveShadow
            geometry={nodes.mesh126_1.geometry}
            material={materials.Black}
          />
        </group>
        <group
          name="Símbolo_de_importación_ubicación_<No_compartido>_12_a7a007"
          position={[0, 0, 12.05]}
        >
          <mesh
            name="mesh127"
            castShadow
            receiveShadow
            geometry={nodes.mesh127.geometry}
            material={materials["Low.002"]}
          />
          <mesh
            name="mesh127_1"
            castShadow
            receiveShadow
            geometry={nodes.mesh127_1.geometry}
            material={materials.Black}
          />
        </group>
        <group
          name="Símbolo_de_importación_ubicación_<No_compartido>_12_a7a008"
          position={[0, 0, 12.05]}
        >
          <mesh
            name="mesh128"
            castShadow
            receiveShadow
            geometry={nodes.mesh128.geometry}
            material={materials["Low.002"]}
          />
          <mesh
            name="mesh128_1"
            castShadow
            receiveShadow
            geometry={nodes.mesh128_1.geometry}
            material={materials.Black}
          />
        </group>
        <group
          name="Símbolo_de_importación_ubicación_<No_compartido>_12_a7a009"
          position={[0, 0, 12.05]}
        >
          <mesh
            name="mesh129"
            castShadow
            receiveShadow
            geometry={nodes.mesh129.geometry}
            material={materials["Low.002"]}
          />
          <mesh
            name="mesh129_1"
            castShadow
            receiveShadow
            geometry={nodes.mesh129_1.geometry}
            material={materials.Black}
          />
        </group>
        <mesh
          name="Símbolo_de_importación_ubicación_<No_compartido>_12_1e4006"
          castShadow
          receiveShadow
          geometry={
            nodes["Símbolo_de_importación_ubicación_<No_compartido>_12_1e4006"]
              .geometry
          }
          material={materials["Low.002"]}
          position={[0, 0, 12.05]}
        />
        <mesh
          name="Símbolo_de_importación_ubicación_<No_compartido>_12_1e4007"
          castShadow
          receiveShadow
          geometry={
            nodes["Símbolo_de_importación_ubicación_<No_compartido>_12_1e4007"]
              .geometry
          }
          material={materials["Low.002"]}
          position={[0, 0, 12.05]}
        />
        <mesh
          name="Símbolo_de_importación_ubicación_<No_compartido>_12_1e4008"
          castShadow
          receiveShadow
          geometry={
            nodes["Símbolo_de_importación_ubicación_<No_compartido>_12_1e4008"]
              .geometry
          }
          material={materials["Low.002"]}
          position={[0, 0, 12.05]}
        />
        <mesh
          name="10202_(Layer_0)035"
          castShadow
          receiveShadow
          geometry={nodes["10202_(Layer_0)035"].geometry}
          material={materials["Low.002"]}
          position={[-60.641, 6.733, 7.723]}
          scale={[1, 1.409, 1]}
        />
        <mesh
          name="10501047"
          castShadow
          receiveShadow
          geometry={nodes["10501047"].geometry}
          material={materials["Paint Gloss Grey #1965"]}
          position={[0, 0, 12.05]}
        />
        <mesh
          name="50002019"
          castShadow
          receiveShadow
          geometry={nodes["50002019"].geometry}
          material={materials["Paint Gloss Grey #1948"]}
          position={[0, 0, 12.05]}
        />
        <mesh
          name="50003023"
          castShadow
          receiveShadow
          geometry={nodes["50003023"].geometry}
          material={materials["Paint Gloss Grey #1949"]}
          position={[0, 0, 12.05]}
        />
        <mesh
          name="50005027"
          castShadow
          receiveShadow
          geometry={nodes["50005027"].geometry}
          material={materials["Paint Gloss Grey #1900"]}
          position={[0, 0, 12.05]}
        />
        <mesh
          name="50005031"
          castShadow
          receiveShadow
          geometry={nodes["50005031"].geometry}
          material={materials["Paint Gloss Grey #1903"]}
          position={[0, 0, 12.05]}
        />
        <mesh
          name="50005043"
          castShadow
          receiveShadow
          geometry={nodes["50005043"].geometry}
          material={materials["Paint Gloss Grey #1950"]}
          position={[0, 0, 12.05]}
        />
        <mesh
          name="50005047"
          castShadow
          receiveShadow
          geometry={nodes["50005047"].geometry}
          material={materials["Paint Gloss Grey #1953"]}
          position={[0, 0, 12.05]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/cvra.glb");

