/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function CVRAModel(props) {
  const { nodes, materials } = useGLTF("/cvra.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh109.geometry}
        material={materials["Low.002"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh109_1.geometry}
        material={materials.Black}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh109_2.geometry}
        material={materials["maleta roja"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh109_3.geometry}
        material={materials.Material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh109_4.geometry}
        material={materials["Paint Gloss Yellow #348.140"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh109_5.geometry}
        material={materials["Paint Gloss Yellow #348.141"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh109_6.geometry}
        material={materials["Paint Gloss Yellow #348.142"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh109_7.geometry}
        material={materials["Paint Gloss Yellow #348.143"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh109_8.geometry}
        material={materials["Paint Matte Grey #1.005"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh109_9.geometry}
        material={materials["Paint Matte Grey #43"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh109_10.geometry}
        material={materials["Paint Matte Grey #1.006"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh109_11.geometry}
        material={materials["Paint Matte Grey #38"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh109_12.geometry}
        material={materials["Paint Matte Grey #36"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh109_13.geometry}
        material={materials["Paint Matte Grey #42"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh109_14.geometry}
        material={materials["Paint Matte Grey #41"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh109_15.geometry}
        material={materials["Paint Matte Grey #1.007"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh109_16.geometry}
        material={materials["Paint Matte Grey #37"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh109_17.geometry}
        material={materials["Paint Matte Grey #35"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh109_18.geometry}
        material={materials["Paint Matte Grey #39"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh109_19.geometry}
        material={materials["METAL AMARILLO"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh109_20.geometry}
        material={materials["Paint Gloss Grey #1965"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh109_21.geometry}
        material={materials["Paint Gloss Grey #1948"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh109_22.geometry}
        material={materials["Paint Gloss Grey #1949"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh109_23.geometry}
        material={materials["Paint Gloss Grey #1900"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh109_24.geometry}
        material={materials["Paint Gloss Grey #1903"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh109_25.geometry}
        material={materials["Paint Gloss Grey #1950"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh109_26.geometry}
        material={materials["Paint Gloss Grey #1953"]}
      />
    </group>
  );
}

useGLTF.preload("/cvra.glb");
