/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function MakeupModel(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/makeup.glb");
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group
          name="62001_(Layer_0)005"
          position={[-6.201, 7.868, -1.652]}
          rotation={[0.019, 0, 0]}
        />
        <group
          name="62001_(Layer_0)001"
          position={[-4.236, -0.01, -21.774]}
          rotation={[0, 0.791, 0]}
        />
        <group name="62001_(Layer_0)002" />
        <group name="62001_(Layer_0)003" position={[-7.75, 0, -9.769]} />
        <group name="62001_(Layer_0)004" position={[-26.676, 7.907, -10.288]} />
        <group
          name="Handle_Cube002"
          position={[5.129, 10.723, 2.031]}
          rotation={[2.854, 0, -3.127]}
        />
        <group
          name="Armature005"
          position={[-28.158, 10.762, 1.651]}
          scale={0.534}
        >
          <primitive object={nodes.Bone} />
        </group>
        <group name="Suelo_Generic_Floor_-_100mm_2_1217029_1010" />
        <mesh
          name="Cylinder432"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder432.geometry}
          material={nodes.Cylinder432.material}
          position={[-49.305, 8.283, -64.421]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={[0.574, 0.574, 2.543]}
        />
        <mesh
          name="Cylinder436"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder436.geometry}
          material={nodes.Cylinder436.material}
          position={[-66.436, 8.283, -64.442]}
          rotation={[-Math.PI / 2, 0, Math.PI / 2]}
          scale={[0.574, 0.574, 2.543]}
        />
        <mesh
          name="Cylinder557"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder557.geometry}
          material={nodes.Cylinder557.material}
          position={[-46.859, 8.302, -59.298]}
          rotation={[-1.571, 0.012, Math.PI / 2]}
          scale={[0.724, 0.769, 0.197]}
        />
        <mesh
          name="Cylinder559"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder559.geometry}
          material={nodes.Cylinder559.material}
          position={[-49.835, 8.363, -59.31]}
          rotation={[-1.571, 0.012, Math.PI / 2]}
          scale={[0.724, 0.723, 0.197]}
        />
        <mesh
          name="CP1_BHS_Flat_Plate_2_393903002"
          castShadow
          receiveShadow
          geometry={nodes.CP1_BHS_Flat_Plate_2_393903002.geometry}
          material={materials.METAL}
          position={[0, 0, -64.191]}
        />
        <mesh
          name="CP1_BHS_Flat_Plate_2_393903_1001"
          castShadow
          receiveShadow
          geometry={nodes.CP1_BHS_Flat_Plate_2_393903_1001.geometry}
          material={materials["Negro.001"]}
          position={[0, 0, -64.191]}
        />
        <mesh
          name="CP1_BHS_Flat_Plate_2_393903003"
          castShadow
          receiveShadow
          geometry={nodes.CP1_BHS_Flat_Plate_2_393903003.geometry}
          material={materials.METAL}
          position={[0, 0, -64.191]}
        />
        <mesh
          name="CP1_BHS_Flat_Plate_2_393903_1002"
          castShadow
          receiveShadow
          geometry={nodes.CP1_BHS_Flat_Plate_2_393903_1002.geometry}
          material={materials["Negro.001"]}
          position={[0, 0, -64.191]}
        />
        <mesh
          name="CP1_BHS_Flat_Plate_2_393903001"
          castShadow
          receiveShadow
          geometry={nodes.CP1_BHS_Flat_Plate_2_393903001.geometry}
          material={materials.METAL}
          position={[0, 0, -64.191]}
        />
        <mesh
          name="CP1_BHS_Flat_Plate_2_393903_1003"
          castShadow
          receiveShadow
          geometry={nodes.CP1_BHS_Flat_Plate_2_393903_1003.geometry}
          material={materials["Negro.001"]}
          position={[0, 0, -64.191]}
        />
        <mesh
          name="Suelo_ANDENES_656127002"
          castShadow
          receiveShadow
          geometry={nodes.Suelo_ANDENES_656127002.geometry}
          material={materials["Low.002"]}
          position={[0, 0, -64.191]}
        />
        <mesh
          name="Suelo_ANDENES_656127003"
          castShadow
          receiveShadow
          geometry={nodes.Suelo_ANDENES_656127003.geometry}
          material={materials["Low.002"]}
          position={[0, 0, -64.191]}
        />
        <group
          name="Transportador_Recto_Horizontal_(20)_Transportador_Recto_8d75fee"
          position={[0, 0, -64.191]}
        >
          <mesh
            name="mesh381"
            castShadow
            receiveShadow
            geometry={nodes.mesh381.geometry}
            material={materials.METAL}
          />
          <mesh
            name="mesh381_1"
            castShadow
            receiveShadow
            geometry={nodes.mesh381_1.geometry}
            material={materials["Negro.001"]}
          />
        </group>
        <group name="10202_(Layer_0)028" position={[0, 0, -64.191]}>
          <mesh
            name="mesh400"
            castShadow
            receiveShadow
            geometry={nodes.mesh400.geometry}
            material={materials.METAL}
          />
          <mesh
            name="mesh400_1"
            castShadow
            receiveShadow
            geometry={nodes.mesh400_1.geometry}
            material={materials["Negro.001"]}
          />
        </group>
        <group name="10202_(Layer_0)030" position={[0, 0, -64.191]}>
          <mesh
            name="mesh402"
            castShadow
            receiveShadow
            geometry={nodes.mesh402.geometry}
            material={materials.METAL}
          />
          <mesh
            name="mesh402_1"
            castShadow
            receiveShadow
            geometry={nodes.mesh402_1.geometry}
            material={materials["Negro.001"]}
          />
        </group>
        <group name="10202_(Layer_0)032" position={[0, 0, -64.191]}>
          <mesh
            name="mesh405"
            castShadow
            receiveShadow
            geometry={nodes.mesh405.geometry}
            material={materials.METAL}
          />
          <mesh
            name="mesh405_1"
            castShadow
            receiveShadow
            geometry={nodes.mesh405_1.geometry}
            material={materials["Negro.001"]}
          />
        </group>
        <mesh
          name="Suelo_ANDENES_656127001"
          castShadow
          receiveShadow
          geometry={nodes.Suelo_ANDENES_656127001.geometry}
          material={materials["Low.002"]}
          position={[0, 0, -64.191]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/makeup.glb");


